/*
 * Generated by asn1c-1.0.0 (http://lionet.info/asn1c)
 * From ASN.1 module "S1AP-IEs"
 * 	found in "../asn1/S1AP-IEs.asn"
 * 	`asn1c -gen-PER -fcompound-names -S ../skeletons`
 */

#include "BitRate.h"

int
BitRate_constraint(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	const INTEGER_t *st = (const INTEGER_t *)sptr;
	long long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	if(asn_INTEGER2long(st, &value)) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value too large (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	if((value >= 0LL && value <= 10000000000LL)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

/*
 * This type is implemented using INTEGER,
 * so here we adjust the DEF accordingly.
 */
asn_per_constraints_t asn_PER_type_BitRate_constr_1 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 34, -1,  0l, 10000000000ull }	/* (0..10000000000) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static const ber_tlv_tag_t asn_DEF_BitRate_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (2 << 2))
};
asn_TYPE_descriptor_t asn_DEF_BitRate = {
	"BitRate",
	"BitRate",
	&asn_OP_INTEGER,
	BitRate_constraint,
	asn_DEF_BitRate_tags_1,
	sizeof(asn_DEF_BitRate_tags_1)
		/sizeof(asn_DEF_BitRate_tags_1[0]), /* 1 */
	asn_DEF_BitRate_tags_1,	/* Same as above */
	sizeof(asn_DEF_BitRate_tags_1)
		/sizeof(asn_DEF_BitRate_tags_1[0]), /* 1 */
	&asn_PER_type_BitRate_constr_1,
	0, 0,	/* No members */
	0	/* No specifics */
};

