/*
 * Generated by asn1c-1.0.0 (http://lionet.info/asn1c)
 * From ASN.1 module "S1AP-IEs"
 * 	found in "../asn1/S1AP-IEs.asn"
 * 	`asn1c -gen-PER -fcompound-names -S ../skeletons`
 */

#ifndef	_CauseNas_H_
#define	_CauseNas_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum CauseNas {
	CauseNas_normal_release	= 0,
	CauseNas_authentication_failure	= 1,
	CauseNas_detach	= 2,
	CauseNas_unspecified	= 3
	/*
	 * Enumeration is extensible
	 */
} e_CauseNas;

/* CauseNas */
typedef long	 CauseNas_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_CauseNas_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_CauseNas;
extern asn_INTEGER_specifics_t asn_SPC_CauseNas_specs_1;
asn_struct_free_f CauseNas_free;
asn_struct_print_f CauseNas_print;
asn_constr_check_f CauseNas_constraint;
ber_type_decoder_f CauseNas_decode_ber;
der_type_encoder_f CauseNas_encode_der;
xer_type_decoder_f CauseNas_decode_xer;
xer_type_encoder_f CauseNas_encode_xer;
per_type_decoder_f CauseNas_decode_uper;
per_type_encoder_f CauseNas_encode_uper;
per_type_decoder_f CauseNas_decode_aper;
per_type_encoder_f CauseNas_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _CauseNas_H_ */
#include <asn_internal.h>
