/*
 * Generated by asn1c-1.0.0 (http://lionet.info/asn1c)
 * From ASN.1 module "S1AP-IEs"
 * 	found in "../asn1/S1AP-IEs.asn"
 * 	`asn1c -gen-PER -fcompound-names -S ../skeletons`
 */

#include "CGI.h"

asn_TYPE_member_t asn_MBR_CGI_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct CGI, pLMNidentity),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PLMNidentity,
		0,	/* Defer constraints checking to the member type */
		&asn_PER_type_TBCD_STRING_constr_1,
		0,
		"pLMNidentity"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct CGI, lAC),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_LAC,
		0,	/* Defer constraints checking to the member type */
		&asn_PER_type_LAC_constr_1,
		0,
		"lAC"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct CGI, cI),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CI,
		0,	/* Defer constraints checking to the member type */
		&asn_PER_type_CI_constr_1,
		0,
		"cI"
		},
	{ ATF_POINTER, 2, offsetof(struct CGI, rAC),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RAC,
		0,	/* Defer constraints checking to the member type */
		&asn_PER_type_RAC_constr_1,
		0,
		"rAC"
		},
	{ ATF_POINTER, 1, offsetof(struct CGI, iE_Extensions),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ProtocolExtensionContainer_173P5,
		0,	/* Defer constraints checking to the member type */
		&asn_PER_type_ProtocolExtensionContainer_173P5_constr_11,
		0,
		"iE-Extensions"
		},
};
static const int asn_MAP_CGI_oms_1[] = { 3, 4 };
static const ber_tlv_tag_t asn_DEF_CGI_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_CGI_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* pLMNidentity */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* lAC */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* cI */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* rAC */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 } /* iE-Extensions */
};
asn_SEQUENCE_specifics_t asn_SPC_CGI_specs_1 = {
	sizeof(struct CGI),
	offsetof(struct CGI, _asn_ctx),
	asn_MAP_CGI_tag2el_1,
	5,	/* Count of tags in the map */
	asn_MAP_CGI_oms_1,	/* Optional members */
	2, 0,	/* Root/Additions */
	4,	/* Start extensions */
	6	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_CGI = {
	"CGI",
	"CGI",
	&asn_OP_SEQUENCE,
	SEQUENCE_constraint,
	asn_DEF_CGI_tags_1,
	sizeof(asn_DEF_CGI_tags_1)
		/sizeof(asn_DEF_CGI_tags_1[0]), /* 1 */
	asn_DEF_CGI_tags_1,	/* Same as above */
	sizeof(asn_DEF_CGI_tags_1)
		/sizeof(asn_DEF_CGI_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_CGI_1,
	5,	/* Elements count */
	&asn_SPC_CGI_specs_1	/* Additional specs */
};

