/*
 * Generated by asn1c-1.0.0 (http://lionet.info/asn1c)
 * From ASN.1 module "S1AP-IEs"
 * 	found in "../asn1/S1AP-IEs.asn"
 * 	`asn1c -gen-PER -fcompound-names -S ../skeletons`
 */

#include "CriticalityDiagnostics.h"

static asn_TYPE_member_t asn_MBR_CriticalityDiagnostics_1[] = {
	{ ATF_POINTER, 5, offsetof(struct CriticalityDiagnostics, procedureCode),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ProcedureCode,
		0,	/* Defer constraints checking to the member type */
		&asn_PER_type_ProcedureCode_constr_1,
		0,
		"procedureCode"
		},
	{ ATF_POINTER, 4, offsetof(struct CriticalityDiagnostics, triggeringMessage),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TriggeringMessage,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"triggeringMessage"
		},
	{ ATF_POINTER, 3, offsetof(struct CriticalityDiagnostics, procedureCriticality),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Criticality,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"procedureCriticality"
		},
	{ ATF_POINTER, 2, offsetof(struct CriticalityDiagnostics, iEsCriticalityDiagnostics),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CriticalityDiagnostics_IE_List,
		0,	/* Defer constraints checking to the member type */
		&asn_PER_type_CriticalityDiagnostics_IE_List_constr_1,
		0,
		"iEsCriticalityDiagnostics"
		},
	{ ATF_POINTER, 1, offsetof(struct CriticalityDiagnostics, iE_Extensions),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ProtocolExtensionContainer_173P8,
		0,	/* Defer constraints checking to the member type */
		&asn_PER_type_ProtocolExtensionContainer_173P8_constr_17,
		0,
		"iE-Extensions"
		},
};
static const int asn_MAP_CriticalityDiagnostics_oms_1[] = { 0, 1, 2, 3, 4 };
static const ber_tlv_tag_t asn_DEF_CriticalityDiagnostics_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_CriticalityDiagnostics_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* procedureCode */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* triggeringMessage */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* procedureCriticality */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* iEsCriticalityDiagnostics */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 } /* iE-Extensions */
};
static asn_SEQUENCE_specifics_t asn_SPC_CriticalityDiagnostics_specs_1 = {
	sizeof(struct CriticalityDiagnostics),
	offsetof(struct CriticalityDiagnostics, _asn_ctx),
	asn_MAP_CriticalityDiagnostics_tag2el_1,
	5,	/* Count of tags in the map */
	asn_MAP_CriticalityDiagnostics_oms_1,	/* Optional members */
	5, 0,	/* Root/Additions */
	4,	/* Start extensions */
	6	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_CriticalityDiagnostics = {
	"CriticalityDiagnostics",
	"CriticalityDiagnostics",
	&asn_OP_SEQUENCE,
	SEQUENCE_constraint,
	asn_DEF_CriticalityDiagnostics_tags_1,
	sizeof(asn_DEF_CriticalityDiagnostics_tags_1)
		/sizeof(asn_DEF_CriticalityDiagnostics_tags_1[0]), /* 1 */
	asn_DEF_CriticalityDiagnostics_tags_1,	/* Same as above */
	sizeof(asn_DEF_CriticalityDiagnostics_tags_1)
		/sizeof(asn_DEF_CriticalityDiagnostics_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_CriticalityDiagnostics_1,
	5,	/* Elements count */
	&asn_SPC_CriticalityDiagnostics_specs_1	/* Additional specs */
};

