/*
 * Generated by asn1c-1.0.0 (http://lionet.info/asn1c)
 * From ASN.1 module "S1AP-IEs"
 * 	found in "../asn1/S1AP-IEs.asn"
 * 	`asn1c -gen-PER -fcompound-names -S ../skeletons`
 */

#ifndef	_CSG_IdList_H_
#define	_CSG_IdList_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct CSG_IdList_Item;

/* CSG-IdList */
typedef struct CSG_IdList {
	A_SEQUENCE_OF(struct CSG_IdList_Item) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CSG_IdList_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CSG_IdList;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "CSG-IdList-Item.h"

#endif	/* _CSG_IdList_H_ */
#include <asn_internal.h>
