/*
 * Generated by asn1c-1.0.0 (http://lionet.info/asn1c)
 * From ASN.1 module "S1AP-IEs"
 * 	found in "../asn1/S1AP-IEs.asn"
 * 	`asn1c -gen-PER -fcompound-names -S ../skeletons`
 */

#ifndef	_CSG_IdList_Item_H_
#define	_CSG_IdList_Item_H_


#include <asn_application.h>

/* Including external dependencies */
#include "CSG-Id.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ProtocolExtensionContainer;

/* CSG-IdList-Item */
typedef struct CSG_IdList_Item {
	CSG_Id_t	 cSG_Id;
	struct ProtocolExtensionContainer	*iE_Extensions	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CSG_IdList_Item_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CSG_IdList_Item;
extern asn_SEQUENCE_specifics_t asn_SPC_CSG_IdList_Item_specs_1;
extern asn_TYPE_member_t asn_MBR_CSG_IdList_Item_1[2];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ProtocolExtensionContainer.h"

#endif	/* _CSG_IdList_Item_H_ */
#include <asn_internal.h>
