/*
 * Generated by asn1c-1.0.0 (http://lionet.info/asn1c)
 * From ASN.1 module "S1AP-PDU-Contents"
 * 	found in "../asn1/S1AP-PDU-Contents.asn"
 * 	`asn1c -gen-PER -fcompound-names -S ../skeletons`
 */

#include "E-RABDataForwardingItem.h"

static asn_TYPE_member_t asn_MBR_E_RABDataForwardingItem_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct E_RABDataForwardingItem, e_RAB_ID),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_E_RAB_ID,
		0,	/* Defer constraints checking to the member type */
		&asn_PER_type_E_RAB_ID_constr_1,
		0,
		"e-RAB-ID"
		},
	{ ATF_POINTER, 5, offsetof(struct E_RABDataForwardingItem, dL_transportLayerAddress),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TransportLayerAddress,
		0,	/* Defer constraints checking to the member type */
		&asn_PER_type_TransportLayerAddress_constr_1,
		0,
		"dL-transportLayerAddress"
		},
	{ ATF_POINTER, 4, offsetof(struct E_RABDataForwardingItem, dL_gTP_TEID),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_GTP_TEID,
		0,	/* Defer constraints checking to the member type */
		&asn_PER_type_GTP_TEID_constr_1,
		0,
		"dL-gTP-TEID"
		},
	{ ATF_POINTER, 3, offsetof(struct E_RABDataForwardingItem, uL_TransportLayerAddress),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TransportLayerAddress,
		0,	/* Defer constraints checking to the member type */
		&asn_PER_type_TransportLayerAddress_constr_1,
		0,
		"uL-TransportLayerAddress"
		},
	{ ATF_POINTER, 2, offsetof(struct E_RABDataForwardingItem, uL_GTP_TEID),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_GTP_TEID,
		0,	/* Defer constraints checking to the member type */
		&asn_PER_type_GTP_TEID_constr_1,
		0,
		"uL-GTP-TEID"
		},
	{ ATF_POINTER, 1, offsetof(struct E_RABDataForwardingItem, iE_Extensions),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ProtocolExtensionContainer_173P48,
		0,	/* Defer constraints checking to the member type */
		&asn_PER_type_ProtocolExtensionContainer_173P48_constr_97,
		0,
		"iE-Extensions"
		},
};
static const int asn_MAP_E_RABDataForwardingItem_oms_1[] = { 1, 2, 3, 4, 5 };
static const ber_tlv_tag_t asn_DEF_E_RABDataForwardingItem_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_E_RABDataForwardingItem_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* e-RAB-ID */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* dL-transportLayerAddress */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* dL-gTP-TEID */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* uL-TransportLayerAddress */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* uL-GTP-TEID */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 } /* iE-Extensions */
};
static asn_SEQUENCE_specifics_t asn_SPC_E_RABDataForwardingItem_specs_1 = {
	sizeof(struct E_RABDataForwardingItem),
	offsetof(struct E_RABDataForwardingItem, _asn_ctx),
	asn_MAP_E_RABDataForwardingItem_tag2el_1,
	6,	/* Count of tags in the map */
	asn_MAP_E_RABDataForwardingItem_oms_1,	/* Optional members */
	5, 0,	/* Root/Additions */
	5,	/* Start extensions */
	7	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_E_RABDataForwardingItem = {
	"E-RABDataForwardingItem",
	"E-RABDataForwardingItem",
	&asn_OP_SEQUENCE,
	SEQUENCE_constraint,
	asn_DEF_E_RABDataForwardingItem_tags_1,
	sizeof(asn_DEF_E_RABDataForwardingItem_tags_1)
		/sizeof(asn_DEF_E_RABDataForwardingItem_tags_1[0]), /* 1 */
	asn_DEF_E_RABDataForwardingItem_tags_1,	/* Same as above */
	sizeof(asn_DEF_E_RABDataForwardingItem_tags_1)
		/sizeof(asn_DEF_E_RABDataForwardingItem_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_E_RABDataForwardingItem_1,
	6,	/* Elements count */
	&asn_SPC_E_RABDataForwardingItem_specs_1	/* Additional specs */
};

