/*
 * Generated by asn1c-1.0.0 (http://lionet.info/asn1c)
 * From ASN.1 module "S1AP-IEs"
 * 	found in "../asn1/S1AP-IEs.asn"
 * 	`asn1c -gen-PER -fcompound-names -S ../skeletons`
 */

#ifndef	_ECGIList_H_
#define	_ECGIList_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct EUTRAN_CGI;

/* ECGIList */
typedef struct ECGIList {
	A_SEQUENCE_OF(struct EUTRAN_CGI) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ECGIList_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ECGIList;
extern asn_SET_OF_specifics_t asn_SPC_ECGIList_specs_1;
extern asn_TYPE_member_t asn_MBR_ECGIList_1[1];
extern asn_per_constraints_t asn_PER_type_ECGIList_constr_1;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "EUTRAN-CGI.h"

#endif	/* _ECGIList_H_ */
#include <asn_internal.h>
