/*
 * Generated by asn1c-1.0.0 (http://lionet.info/asn1c)
 * From ASN.1 module "S1AP-IEs"
 * 	found in "../asn1/S1AP-IEs.asn"
 * 	`asn1c -gen-PER -fcompound-names -S ../skeletons`
 */

#include "ENB-StatusTransfer-TransparentContainer.h"

static asn_TYPE_member_t asn_MBR_ENB_StatusTransfer_TransparentContainer_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ENB_StatusTransfer_TransparentContainer, bearers_SubjectToStatusTransferList),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Bearers_SubjectToStatusTransferList,
		0,	/* Defer constraints checking to the member type */
		&asn_PER_type_Bearers_SubjectToStatusTransferList_constr_1,
		0,
		"bearers-SubjectToStatusTransferList"
		},
	{ ATF_POINTER, 1, offsetof(struct ENB_StatusTransfer_TransparentContainer, iE_Extensions),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ProtocolExtensionContainer_173P14,
		0,	/* Defer constraints checking to the member type */
		&asn_PER_type_ProtocolExtensionContainer_173P14_constr_29,
		0,
		"iE-Extensions"
		},
};
static const int asn_MAP_ENB_StatusTransfer_TransparentContainer_oms_1[] = { 1 };
static const ber_tlv_tag_t asn_DEF_ENB_StatusTransfer_TransparentContainer_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_ENB_StatusTransfer_TransparentContainer_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* bearers-SubjectToStatusTransferList */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* iE-Extensions */
};
static asn_SEQUENCE_specifics_t asn_SPC_ENB_StatusTransfer_TransparentContainer_specs_1 = {
	sizeof(struct ENB_StatusTransfer_TransparentContainer),
	offsetof(struct ENB_StatusTransfer_TransparentContainer, _asn_ctx),
	asn_MAP_ENB_StatusTransfer_TransparentContainer_tag2el_1,
	2,	/* Count of tags in the map */
	asn_MAP_ENB_StatusTransfer_TransparentContainer_oms_1,	/* Optional members */
	1, 0,	/* Root/Additions */
	1,	/* Start extensions */
	3	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_ENB_StatusTransfer_TransparentContainer = {
	"ENB-StatusTransfer-TransparentContainer",
	"ENB-StatusTransfer-TransparentContainer",
	&asn_OP_SEQUENCE,
	SEQUENCE_constraint,
	asn_DEF_ENB_StatusTransfer_TransparentContainer_tags_1,
	sizeof(asn_DEF_ENB_StatusTransfer_TransparentContainer_tags_1)
		/sizeof(asn_DEF_ENB_StatusTransfer_TransparentContainer_tags_1[0]), /* 1 */
	asn_DEF_ENB_StatusTransfer_TransparentContainer_tags_1,	/* Same as above */
	sizeof(asn_DEF_ENB_StatusTransfer_TransparentContainer_tags_1)
		/sizeof(asn_DEF_ENB_StatusTransfer_TransparentContainer_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_ENB_StatusTransfer_TransparentContainer_1,
	2,	/* Elements count */
	&asn_SPC_ENB_StatusTransfer_TransparentContainer_specs_1	/* Additional specs */
};

