/*
 * Generated by asn1c-1.0.0 (http://lionet.info/asn1c)
 * From ASN.1 module "S1AP-IEs"
 * 	found in "../asn1/S1AP-IEs.asn"
 * 	`asn1c -gen-PER -fcompound-names -S ../skeletons`
 */

#ifndef	_ENB_StatusTransfer_TransparentContainer_H_
#define	_ENB_StatusTransfer_TransparentContainer_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Bearers-SubjectToStatusTransferList.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ProtocolExtensionContainer;

/* ENB-StatusTransfer-TransparentContainer */
typedef struct ENB_StatusTransfer_TransparentContainer {
	Bearers_SubjectToStatusTransferList_t	 bearers_SubjectToStatusTransferList;
	struct ProtocolExtensionContainer	*iE_Extensions	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ENB_StatusTransfer_TransparentContainer_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ENB_StatusTransfer_TransparentContainer;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ProtocolExtensionContainer.h"

#endif	/* _ENB_StatusTransfer_TransparentContainer_H_ */
#include <asn_internal.h>
