/*
 * Generated by asn1c-1.0.0 (http://lionet.info/asn1c)
 * From ASN.1 module "S1AP-IEs"
 * 	found in "../asn1/S1AP-IEs.asn"
 * 	`asn1c -gen-PER -fcompound-names -S ../skeletons`
 */

#include "ENB-UE-S1AP-ID.h"

int
ENB_UE_S1AP_ID_constraint(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long long *)sptr;
	
	if((value >= 0LL && value <= 16777215LL)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

/*
 * This type is implemented using NativeInteger,
 * so here we adjust the DEF accordingly.
 */
asn_per_constraints_t asn_PER_type_ENB_UE_S1AP_ID_constr_1 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 24, -1,  0l,  16777215l }	/* (0..16777215) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static const ber_tlv_tag_t asn_DEF_ENB_UE_S1AP_ID_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (2 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ENB_UE_S1AP_ID = {
	"ENB-UE-S1AP-ID",
	"ENB-UE-S1AP-ID",
	&asn_OP_NativeInteger,
	ENB_UE_S1AP_ID_constraint,
	asn_DEF_ENB_UE_S1AP_ID_tags_1,
	sizeof(asn_DEF_ENB_UE_S1AP_ID_tags_1)
		/sizeof(asn_DEF_ENB_UE_S1AP_ID_tags_1[0]), /* 1 */
	asn_DEF_ENB_UE_S1AP_ID_tags_1,	/* Same as above */
	sizeof(asn_DEF_ENB_UE_S1AP_ID_tags_1)
		/sizeof(asn_DEF_ENB_UE_S1AP_ID_tags_1[0]), /* 1 */
	&asn_PER_type_ENB_UE_S1AP_ID_constr_1,
	0, 0,	/* No members */
	0	/* No specifics */
};

