/*
 * Generated by asn1c-1.0.0 (http://lionet.info/asn1c)
 * From ASN.1 module "S1AP-IEs"
 * 	found in "../asn1/S1AP-IEs.asn"
 * 	`asn1c -gen-PER -fcompound-names -S ../skeletons`
 */

#ifndef	_ENBX2TLAs_H_
#define	_ENBX2TLAs_H_


#include <asn_application.h>

/* Including external dependencies */
#include "TransportLayerAddress.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ENBX2TLAs */
typedef struct ENBX2TLAs {
	A_SEQUENCE_OF(TransportLayerAddress_t) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ENBX2TLAs_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ENBX2TLAs;
extern asn_SET_OF_specifics_t asn_SPC_ENBX2TLAs_specs_1;
extern asn_TYPE_member_t asn_MBR_ENBX2TLAs_1[1];
extern asn_per_constraints_t asn_PER_type_ENBX2TLAs_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _ENBX2TLAs_H_ */
#include <asn_internal.h>
