/*
 * Generated by asn1c-1.0.0 (http://lionet.info/asn1c)
 * From ASN.1 module "S1AP-IEs"
 * 	found in "../asn1/S1AP-IEs.asn"
 * 	`asn1c -gen-PER -fcompound-names -S ../skeletons`
 */

#ifndef	_EUTRAN_CGI_H_
#define	_EUTRAN_CGI_H_


#include <asn_application.h>

/* Including external dependencies */
#include "PLMNidentity.h"
#include "CellIdentity.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ProtocolExtensionContainer;

/* EUTRAN-CGI */
typedef struct EUTRAN_CGI {
	PLMNidentity_t	 pLMNidentity;
	CellIdentity_t	 cell_ID;
	struct ProtocolExtensionContainer	*iE_Extensions	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} EUTRAN_CGI_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_EUTRAN_CGI;
extern asn_SEQUENCE_specifics_t asn_SPC_EUTRAN_CGI_specs_1;
extern asn_TYPE_member_t asn_MBR_EUTRAN_CGI_1[3];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ProtocolExtensionContainer.h"

#endif	/* _EUTRAN_CGI_H_ */
#include <asn_internal.h>
