/*
 * Generated by asn1c-1.0.0 (http://lionet.info/asn1c)
 * From ASN.1 module "S1AP-IEs"
 * 	found in "../asn1/S1AP-IEs.asn"
 * 	`asn1c -gen-PER -fcompound-names -S ../skeletons`
 */

#include "GUMMEI.h"

static asn_TYPE_member_t asn_MBR_GUMMEI_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct GUMMEI, pLMN_Identity),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PLMNidentity,
		0,	/* Defer constraints checking to the member type */
		&asn_PER_type_TBCD_STRING_constr_1,
		0,
		"pLMN-Identity"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct GUMMEI, mME_Group_ID),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MME_Group_ID,
		0,	/* Defer constraints checking to the member type */
		&asn_PER_type_MME_Group_ID_constr_1,
		0,
		"mME-Group-ID"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct GUMMEI, mME_Code),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MME_Code,
		0,	/* Defer constraints checking to the member type */
		&asn_PER_type_MME_Code_constr_1,
		0,
		"mME-Code"
		},
	{ ATF_POINTER, 1, offsetof(struct GUMMEI, iE_Extensions),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ProtocolExtensionContainer_173P22,
		0,	/* Defer constraints checking to the member type */
		&asn_PER_type_ProtocolExtensionContainer_173P22_constr_45,
		0,
		"iE-Extensions"
		},
};
static const int asn_MAP_GUMMEI_oms_1[] = { 3 };
static const ber_tlv_tag_t asn_DEF_GUMMEI_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_GUMMEI_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* pLMN-Identity */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* mME-Group-ID */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* mME-Code */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 } /* iE-Extensions */
};
static asn_SEQUENCE_specifics_t asn_SPC_GUMMEI_specs_1 = {
	sizeof(struct GUMMEI),
	offsetof(struct GUMMEI, _asn_ctx),
	asn_MAP_GUMMEI_tag2el_1,
	4,	/* Count of tags in the map */
	asn_MAP_GUMMEI_oms_1,	/* Optional members */
	1, 0,	/* Root/Additions */
	3,	/* Start extensions */
	5	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_GUMMEI = {
	"GUMMEI",
	"GUMMEI",
	&asn_OP_SEQUENCE,
	SEQUENCE_constraint,
	asn_DEF_GUMMEI_tags_1,
	sizeof(asn_DEF_GUMMEI_tags_1)
		/sizeof(asn_DEF_GUMMEI_tags_1[0]), /* 1 */
	asn_DEF_GUMMEI_tags_1,	/* Same as above */
	sizeof(asn_DEF_GUMMEI_tags_1)
		/sizeof(asn_DEF_GUMMEI_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_GUMMEI_1,
	4,	/* Elements count */
	&asn_SPC_GUMMEI_specs_1	/* Additional specs */
};

