/*
 * Generated by asn1c-1.0.0 (http://lionet.info/asn1c)
 * From ASN.1 module "S1AP-IEs"
 * 	found in "../asn1/S1AP-IEs.asn"
 * 	`asn1c -gen-PER -fcompound-names -S ../skeletons`
 */

#ifndef	_GUMMEI_H_
#define	_GUMMEI_H_


#include <asn_application.h>

/* Including external dependencies */
#include "PLMNidentity.h"
#include "MME-Group-ID.h"
#include "MME-Code.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ProtocolExtensionContainer;

/* GUMMEI */
typedef struct GUMMEI {
	PLMNidentity_t	 pLMN_Identity;
	MME_Group_ID_t	 mME_Group_ID;
	MME_Code_t	 mME_Code;
	struct ProtocolExtensionContainer	*iE_Extensions	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} GUMMEI_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_GUMMEI;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ProtocolExtensionContainer.h"

#endif	/* _GUMMEI_H_ */
#include <asn_internal.h>
