/*
 * Generated by asn1c-1.0.0 (http://lionet.info/asn1c)
 * From ASN.1 module "S1AP-PDU-Contents"
 * 	found in "../asn1/S1AP-PDU-Contents.asn"
 * 	`asn1c -gen-PER -fcompound-names -S ../skeletons`
 */

#include "Inter-SystemInformationTransferType.h"

static asn_per_constraints_t asn_PER_type_Inter_SystemInformationTransferType_constr_1 GCC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  0,  0,  0l,  0l }	/* (0..0,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_Inter_SystemInformationTransferType_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct Inter_SystemInformationTransferType, choice.rIMTransfer),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RIMTransfer,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"rIMTransfer"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_Inter_SystemInformationTransferType_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 } /* rIMTransfer */
};
static asn_CHOICE_specifics_t asn_SPC_Inter_SystemInformationTransferType_specs_1 = {
	sizeof(struct Inter_SystemInformationTransferType),
	offsetof(struct Inter_SystemInformationTransferType, _asn_ctx),
	offsetof(struct Inter_SystemInformationTransferType, present),
	sizeof(((struct Inter_SystemInformationTransferType *)0)->present),
	asn_MAP_Inter_SystemInformationTransferType_tag2el_1,
	1,	/* Count of tags in the map */
	0,
	1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_Inter_SystemInformationTransferType = {
	"Inter-SystemInformationTransferType",
	"Inter-SystemInformationTransferType",
	&asn_OP_CHOICE,
	CHOICE_constraint,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	&asn_PER_type_Inter_SystemInformationTransferType_constr_1,
	asn_MBR_Inter_SystemInformationTransferType_1,
	1,	/* Elements count */
	&asn_SPC_Inter_SystemInformationTransferType_specs_1	/* Additional specs */
};

