/*
 * Generated by asn1c-1.0.0 (http://lionet.info/asn1c)
 * From ASN.1 module "S1AP-IEs"
 * 	found in "../asn1/S1AP-IEs.asn"
 * 	`asn1c -gen-PER -fcompound-names -S ../skeletons`
 */

#include "LastVisitedCell-Item.h"

asn_per_constraints_t asn_PER_type_LastVisitedCell_Item_constr_1 GCC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  2,  2,  0l,  2l }	/* (0..2,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
asn_TYPE_member_t asn_MBR_LastVisitedCell_Item_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct LastVisitedCell_Item, choice.e_UTRAN_Cell),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_LastVisitedEUTRANCellInformation,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"e-UTRAN-Cell"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LastVisitedCell_Item, choice.uTRAN_Cell),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_LastVisitedUTRANCellInformation,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uTRAN-Cell"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LastVisitedCell_Item, choice.gERAN_Cell),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_LastVisitedGERANCellInformation,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"gERAN-Cell"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_LastVisitedCell_Item_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* e-UTRAN-Cell */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* uTRAN-Cell */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* gERAN-Cell */
};
asn_CHOICE_specifics_t asn_SPC_LastVisitedCell_Item_specs_1 = {
	sizeof(struct LastVisitedCell_Item),
	offsetof(struct LastVisitedCell_Item, _asn_ctx),
	offsetof(struct LastVisitedCell_Item, present),
	sizeof(((struct LastVisitedCell_Item *)0)->present),
	asn_MAP_LastVisitedCell_Item_tag2el_1,
	3,	/* Count of tags in the map */
	0,
	3	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_LastVisitedCell_Item = {
	"LastVisitedCell-Item",
	"LastVisitedCell-Item",
	&asn_OP_CHOICE,
	CHOICE_constraint,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	&asn_PER_type_LastVisitedCell_Item_constr_1,
	asn_MBR_LastVisitedCell_Item_1,
	3,	/* Elements count */
	&asn_SPC_LastVisitedCell_Item_specs_1	/* Additional specs */
};

