/*
 * Generated by asn1c-1.0.0 (http://lionet.info/asn1c)
 * From ASN.1 module "S1AP-IEs"
 * 	found in "../asn1/S1AP-IEs.asn"
 * 	`asn1c -gen-PER -fcompound-names -S ../skeletons`
 */

#ifndef	_NumberofBroadcast_H_
#define	_NumberofBroadcast_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* NumberofBroadcast */
typedef long	 NumberofBroadcast_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NumberofBroadcast;
asn_struct_free_f NumberofBroadcast_free;
asn_struct_print_f NumberofBroadcast_print;
asn_constr_check_f NumberofBroadcast_constraint;
ber_type_decoder_f NumberofBroadcast_decode_ber;
der_type_encoder_f NumberofBroadcast_encode_der;
xer_type_decoder_f NumberofBroadcast_decode_xer;
xer_type_encoder_f NumberofBroadcast_encode_xer;
per_type_decoder_f NumberofBroadcast_decode_uper;
per_type_encoder_f NumberofBroadcast_encode_uper;
per_type_decoder_f NumberofBroadcast_decode_aper;
per_type_encoder_f NumberofBroadcast_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _NumberofBroadcast_H_ */
#include <asn_internal.h>
