/*
 * Generated by asn1c-1.0.0 (http://lionet.info/asn1c)
 * From ASN.1 module "S1AP-IEs"
 * 	found in "../asn1/S1AP-IEs.asn"
 * 	`asn1c -gen-PER -fcompound-names -S ../skeletons`
 */

#ifndef	_PLMNidentity_H_
#define	_PLMNidentity_H_


#include <asn_application.h>

/* Including external dependencies */
#include "TBCD-STRING.h"

#ifdef __cplusplus
extern "C" {
#endif

/* PLMNidentity */
typedef TBCD_STRING_t	 PLMNidentity_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PLMNidentity;
asn_struct_free_f PLMNidentity_free;
asn_struct_print_f PLMNidentity_print;
asn_constr_check_f PLMNidentity_constraint;
ber_type_decoder_f PLMNidentity_decode_ber;
der_type_encoder_f PLMNidentity_encode_der;
xer_type_decoder_f PLMNidentity_decode_xer;
xer_type_encoder_f PLMNidentity_encode_xer;
per_type_decoder_f PLMNidentity_decode_uper;
per_type_encoder_f PLMNidentity_encode_uper;
per_type_decoder_f PLMNidentity_decode_aper;
per_type_encoder_f PLMNidentity_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _PLMNidentity_H_ */
#include <asn_internal.h>
