/*
 * Generated by asn1c-1.0.0 (http://lionet.info/asn1c)
 * From ASN.1 module "S1AP-Containers"
 * 	found in "../asn1/S1AP-Containers.asn"
 * 	`asn1c -gen-PER -fcompound-names -S ../skeletons`
 */

#ifndef	_ProtocolIE_ContainerList_H_
#define	_ProtocolIE_ContainerList_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ProtocolIE_Field;

/* ProtocolIE-ContainerList */
typedef struct ProtocolIE_ContainerList_159P0 {
	A_SEQUENCE_OF(struct ProtocolIE_Field) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_ContainerList_159P0_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_ContainerList_159P0;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_ContainerList_159P0_specs_1;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_ContainerList_159P0_1[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_ContainerList_159P0_constr_1;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ProtocolIE-Field.h"

#endif	/* _ProtocolIE_ContainerList_H_ */
#include <asn_internal.h>
