/*
 * Generated by asn1c-1.0.0 (http://lionet.info/asn1c)
 * From ASN.1 module "S1AP-Containers"
 * 	found in "../asn1/S1AP-Containers.asn"
 * 	`asn1c -gen-PER -fcompound-names -S ../skeletons`
 */

#include "ProtocolIE-SingleContainer.h"

/*
 * This type is implemented using ProtocolIE_Field_128P0,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using ProtocolIE_Field_128P0,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using ProtocolIE_Field_128P0,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using ProtocolIE_Field_128P0,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using ProtocolIE_Field_128P0,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using ProtocolIE_Field_128P0,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using ProtocolIE_Field_128P0,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using ProtocolIE_Field_128P0,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using ProtocolIE_Field_128P0,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using ProtocolIE_Field_128P0,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using ProtocolIE_Field_128P0,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using ProtocolIE_Field_128P0,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using ProtocolIE_Field_128P0,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using ProtocolIE_Field_128P0,
 * so here we adjust the DEF accordingly.
 */
static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_125P0_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_125P0 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	SEQUENCE_constraint,
	asn_DEF_ProtocolIE_SingleContainer_125P0_tags_1,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_125P0_tags_1)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_125P0_tags_1[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_125P0_tags_1,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_125P0_tags_1)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_125P0_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_ProtocolIE_Field_128P0_1,
	3,	/* Elements count */
	&asn_SPC_ProtocolIE_Field_128P0_specs_1	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_125P1_tags_2[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_125P1 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	SEQUENCE_constraint,
	asn_DEF_ProtocolIE_SingleContainer_125P1_tags_2,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_125P1_tags_2)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_125P1_tags_2[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_125P1_tags_2,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_125P1_tags_2)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_125P1_tags_2[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_ProtocolIE_Field_128P0_1,
	3,	/* Elements count */
	&asn_SPC_ProtocolIE_Field_128P0_specs_1	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_125P2_tags_3[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_125P2 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	SEQUENCE_constraint,
	asn_DEF_ProtocolIE_SingleContainer_125P2_tags_3,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_125P2_tags_3)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_125P2_tags_3[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_125P2_tags_3,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_125P2_tags_3)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_125P2_tags_3[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_ProtocolIE_Field_128P0_1,
	3,	/* Elements count */
	&asn_SPC_ProtocolIE_Field_128P0_specs_1	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_125P3_tags_4[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_125P3 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	SEQUENCE_constraint,
	asn_DEF_ProtocolIE_SingleContainer_125P3_tags_4,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_125P3_tags_4)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_125P3_tags_4[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_125P3_tags_4,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_125P3_tags_4)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_125P3_tags_4[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_ProtocolIE_Field_128P0_1,
	3,	/* Elements count */
	&asn_SPC_ProtocolIE_Field_128P0_specs_1	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_125P4_tags_5[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_125P4 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	SEQUENCE_constraint,
	asn_DEF_ProtocolIE_SingleContainer_125P4_tags_5,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_125P4_tags_5)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_125P4_tags_5[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_125P4_tags_5,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_125P4_tags_5)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_125P4_tags_5[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_ProtocolIE_Field_128P0_1,
	3,	/* Elements count */
	&asn_SPC_ProtocolIE_Field_128P0_specs_1	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_125P5_tags_6[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_125P5 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	SEQUENCE_constraint,
	asn_DEF_ProtocolIE_SingleContainer_125P5_tags_6,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_125P5_tags_6)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_125P5_tags_6[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_125P5_tags_6,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_125P5_tags_6)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_125P5_tags_6[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_ProtocolIE_Field_128P0_1,
	3,	/* Elements count */
	&asn_SPC_ProtocolIE_Field_128P0_specs_1	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_125P6_tags_7[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_125P6 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	SEQUENCE_constraint,
	asn_DEF_ProtocolIE_SingleContainer_125P6_tags_7,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_125P6_tags_7)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_125P6_tags_7[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_125P6_tags_7,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_125P6_tags_7)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_125P6_tags_7[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_ProtocolIE_Field_128P0_1,
	3,	/* Elements count */
	&asn_SPC_ProtocolIE_Field_128P0_specs_1	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_125P7_tags_8[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_125P7 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	SEQUENCE_constraint,
	asn_DEF_ProtocolIE_SingleContainer_125P7_tags_8,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_125P7_tags_8)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_125P7_tags_8[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_125P7_tags_8,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_125P7_tags_8)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_125P7_tags_8[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_ProtocolIE_Field_128P0_1,
	3,	/* Elements count */
	&asn_SPC_ProtocolIE_Field_128P0_specs_1	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_125P8_tags_9[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_125P8 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	SEQUENCE_constraint,
	asn_DEF_ProtocolIE_SingleContainer_125P8_tags_9,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_125P8_tags_9)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_125P8_tags_9[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_125P8_tags_9,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_125P8_tags_9)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_125P8_tags_9[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_ProtocolIE_Field_128P0_1,
	3,	/* Elements count */
	&asn_SPC_ProtocolIE_Field_128P0_specs_1	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_125P9_tags_10[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_125P9 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	SEQUENCE_constraint,
	asn_DEF_ProtocolIE_SingleContainer_125P9_tags_10,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_125P9_tags_10)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_125P9_tags_10[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_125P9_tags_10,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_125P9_tags_10)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_125P9_tags_10[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_ProtocolIE_Field_128P0_1,
	3,	/* Elements count */
	&asn_SPC_ProtocolIE_Field_128P0_specs_1	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_125P10_tags_11[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_125P10 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	SEQUENCE_constraint,
	asn_DEF_ProtocolIE_SingleContainer_125P10_tags_11,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_125P10_tags_11)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_125P10_tags_11[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_125P10_tags_11,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_125P10_tags_11)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_125P10_tags_11[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_ProtocolIE_Field_128P0_1,
	3,	/* Elements count */
	&asn_SPC_ProtocolIE_Field_128P0_specs_1	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_125P11_tags_12[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_125P11 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	SEQUENCE_constraint,
	asn_DEF_ProtocolIE_SingleContainer_125P11_tags_12,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_125P11_tags_12)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_125P11_tags_12[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_125P11_tags_12,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_125P11_tags_12)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_125P11_tags_12[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_ProtocolIE_Field_128P0_1,
	3,	/* Elements count */
	&asn_SPC_ProtocolIE_Field_128P0_specs_1	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_125P12_tags_13[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_125P12 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	SEQUENCE_constraint,
	asn_DEF_ProtocolIE_SingleContainer_125P12_tags_13,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_125P12_tags_13)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_125P12_tags_13[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_125P12_tags_13,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_125P12_tags_13)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_125P12_tags_13[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_ProtocolIE_Field_128P0_1,
	3,	/* Elements count */
	&asn_SPC_ProtocolIE_Field_128P0_specs_1	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_125P13_tags_0[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_125P13 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	SEQUENCE_constraint,
	asn_DEF_ProtocolIE_SingleContainer_125P13_tags_0,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_125P13_tags_0)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_125P13_tags_0[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_125P13_tags_0,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_125P13_tags_0)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_125P13_tags_0[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_ProtocolIE_Field_128P0_1,
	3,	/* Elements count */
	&asn_SPC_ProtocolIE_Field_128P0_specs_1	/* Additional specs */
};

