/*
 * Generated by asn1c-1.0.0 (http://lionet.info/asn1c)
 * From ASN.1 module "S1AP-Containers"
 * 	found in "../asn1/S1AP-Containers.asn"
 * 	`asn1c -gen-PER -fcompound-names -S ../skeletons`
 */

#ifndef	_ProtocolIE_Field_H_
#define	_ProtocolIE_Field_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ProtocolIE-ID.h"
#include "Criticality.h"
#include <ANY.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ProtocolIE-Field */
typedef struct ProtocolIE_Field_128P0 {
	ProtocolIE_ID_t	 id;
	Criticality_t	 criticality;
	ANY_t	 value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Field_128P0_t;
typedef struct ProtocolIE_Field_128P1 {
	ProtocolIE_ID_t	 id;
	Criticality_t	 criticality;
	ANY_t	 value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Field_128P1_t;
typedef struct ProtocolIE_Field_128P2 {
	ProtocolIE_ID_t	 id;
	Criticality_t	 criticality;
	ANY_t	 value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Field_128P2_t;
typedef struct ProtocolIE_Field_128P3 {
	ProtocolIE_ID_t	 id;
	Criticality_t	 criticality;
	ANY_t	 value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Field_128P3_t;
typedef struct ProtocolIE_Field_128P4 {
	ProtocolIE_ID_t	 id;
	Criticality_t	 criticality;
	ANY_t	 value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Field_128P4_t;
typedef struct ProtocolIE_Field_128P5 {
	ProtocolIE_ID_t	 id;
	Criticality_t	 criticality;
	ANY_t	 value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Field_128P5_t;
typedef struct ProtocolIE_Field_128P6 {
	ProtocolIE_ID_t	 id;
	Criticality_t	 criticality;
	ANY_t	 value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Field_128P6_t;
typedef struct ProtocolIE_Field_128P7 {
	ProtocolIE_ID_t	 id;
	Criticality_t	 criticality;
	ANY_t	 value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Field_128P7_t;
typedef struct ProtocolIE_Field_128P8 {
	ProtocolIE_ID_t	 id;
	Criticality_t	 criticality;
	ANY_t	 value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Field_128P8_t;
typedef struct ProtocolIE_Field_128P9 {
	ProtocolIE_ID_t	 id;
	Criticality_t	 criticality;
	ANY_t	 value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Field_128P9_t;
typedef struct ProtocolIE_Field_128P10 {
	ProtocolIE_ID_t	 id;
	Criticality_t	 criticality;
	ANY_t	 value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Field_128P10_t;
typedef struct ProtocolIE_Field_128P11 {
	ProtocolIE_ID_t	 id;
	Criticality_t	 criticality;
	ANY_t	 value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Field_128P11_t;
typedef struct ProtocolIE_Field_128P12 {
	ProtocolIE_ID_t	 id;
	Criticality_t	 criticality;
	ANY_t	 value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Field_128P12_t;
typedef struct ProtocolIE_Field_128P13 {
	ProtocolIE_ID_t	 id;
	Criticality_t	 criticality;
	ANY_t	 value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Field_128P13_t;
typedef struct ProtocolIE_Field_128P14 {
	ProtocolIE_ID_t	 id;
	Criticality_t	 criticality;
	ANY_t	 value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Field_128P14_t;
typedef struct ProtocolIE_Field_128P15 {
	ProtocolIE_ID_t	 id;
	Criticality_t	 criticality;
	ANY_t	 value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Field_128P15_t;
typedef struct ProtocolIE_Field_128P16 {
	ProtocolIE_ID_t	 id;
	Criticality_t	 criticality;
	ANY_t	 value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Field_128P16_t;
typedef struct ProtocolIE_Field_128P17 {
	ProtocolIE_ID_t	 id;
	Criticality_t	 criticality;
	ANY_t	 value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Field_128P17_t;
typedef struct ProtocolIE_Field_128P18 {
	ProtocolIE_ID_t	 id;
	Criticality_t	 criticality;
	ANY_t	 value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Field_128P18_t;
typedef struct ProtocolIE_Field_128P19 {
	ProtocolIE_ID_t	 id;
	Criticality_t	 criticality;
	ANY_t	 value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Field_128P19_t;
typedef struct ProtocolIE_Field_128P20 {
	ProtocolIE_ID_t	 id;
	Criticality_t	 criticality;
	ANY_t	 value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Field_128P20_t;
typedef struct ProtocolIE_Field_128P21 {
	ProtocolIE_ID_t	 id;
	Criticality_t	 criticality;
	ANY_t	 value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Field_128P21_t;
typedef struct ProtocolIE_Field_128P22 {
	ProtocolIE_ID_t	 id;
	Criticality_t	 criticality;
	ANY_t	 value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Field_128P22_t;
typedef struct ProtocolIE_Field_128P23 {
	ProtocolIE_ID_t	 id;
	Criticality_t	 criticality;
	ANY_t	 value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Field_128P23_t;
typedef struct ProtocolIE_Field_128P24 {
	ProtocolIE_ID_t	 id;
	Criticality_t	 criticality;
	ANY_t	 value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Field_128P24_t;
typedef struct ProtocolIE_Field_128P25 {
	ProtocolIE_ID_t	 id;
	Criticality_t	 criticality;
	ANY_t	 value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Field_128P25_t;
typedef struct ProtocolIE_Field_128P26 {
	ProtocolIE_ID_t	 id;
	Criticality_t	 criticality;
	ANY_t	 value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Field_128P26_t;
typedef struct ProtocolIE_Field_128P27 {
	ProtocolIE_ID_t	 id;
	Criticality_t	 criticality;
	ANY_t	 value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Field_128P27_t;
typedef struct ProtocolIE_Field_128P28 {
	ProtocolIE_ID_t	 id;
	Criticality_t	 criticality;
	ANY_t	 value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Field_128P28_t;
typedef struct ProtocolIE_Field_128P29 {
	ProtocolIE_ID_t	 id;
	Criticality_t	 criticality;
	ANY_t	 value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Field_128P29_t;
typedef struct ProtocolIE_Field_128P30 {
	ProtocolIE_ID_t	 id;
	Criticality_t	 criticality;
	ANY_t	 value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Field_128P30_t;
typedef struct ProtocolIE_Field_128P31 {
	ProtocolIE_ID_t	 id;
	Criticality_t	 criticality;
	ANY_t	 value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Field_128P31_t;
typedef struct ProtocolIE_Field_128P32 {
	ProtocolIE_ID_t	 id;
	Criticality_t	 criticality;
	ANY_t	 value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Field_128P32_t;
typedef struct ProtocolIE_Field_128P33 {
	ProtocolIE_ID_t	 id;
	Criticality_t	 criticality;
	ANY_t	 value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Field_128P33_t;
typedef struct ProtocolIE_Field_128P34 {
	ProtocolIE_ID_t	 id;
	Criticality_t	 criticality;
	ANY_t	 value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Field_128P34_t;
typedef struct ProtocolIE_Field_128P35 {
	ProtocolIE_ID_t	 id;
	Criticality_t	 criticality;
	ANY_t	 value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Field_128P35_t;
typedef struct ProtocolIE_Field_128P36 {
	ProtocolIE_ID_t	 id;
	Criticality_t	 criticality;
	ANY_t	 value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Field_128P36_t;
typedef struct ProtocolIE_Field_128P37 {
	ProtocolIE_ID_t	 id;
	Criticality_t	 criticality;
	ANY_t	 value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Field_128P37_t;
typedef struct ProtocolIE_Field_128P38 {
	ProtocolIE_ID_t	 id;
	Criticality_t	 criticality;
	ANY_t	 value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Field_128P38_t;
typedef struct ProtocolIE_Field_128P39 {
	ProtocolIE_ID_t	 id;
	Criticality_t	 criticality;
	ANY_t	 value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Field_128P39_t;
typedef struct ProtocolIE_Field_128P40 {
	ProtocolIE_ID_t	 id;
	Criticality_t	 criticality;
	ANY_t	 value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Field_128P40_t;
typedef struct ProtocolIE_Field_128P41 {
	ProtocolIE_ID_t	 id;
	Criticality_t	 criticality;
	ANY_t	 value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Field_128P41_t;
typedef struct ProtocolIE_Field_128P42 {
	ProtocolIE_ID_t	 id;
	Criticality_t	 criticality;
	ANY_t	 value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Field_128P42_t;
typedef struct ProtocolIE_Field_128P43 {
	ProtocolIE_ID_t	 id;
	Criticality_t	 criticality;
	ANY_t	 value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Field_128P43_t;
typedef struct ProtocolIE_Field_128P44 {
	ProtocolIE_ID_t	 id;
	Criticality_t	 criticality;
	ANY_t	 value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Field_128P44_t;
typedef struct ProtocolIE_Field_128P45 {
	ProtocolIE_ID_t	 id;
	Criticality_t	 criticality;
	ANY_t	 value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Field_128P45_t;
typedef struct ProtocolIE_Field_128P46 {
	ProtocolIE_ID_t	 id;
	Criticality_t	 criticality;
	ANY_t	 value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Field_128P46_t;
typedef struct ProtocolIE_Field_128P47 {
	ProtocolIE_ID_t	 id;
	Criticality_t	 criticality;
	ANY_t	 value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Field_128P47_t;
typedef struct ProtocolIE_Field_128P48 {
	ProtocolIE_ID_t	 id;
	Criticality_t	 criticality;
	ANY_t	 value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Field_128P48_t;
typedef struct ProtocolIE_Field_128P49 {
	ProtocolIE_ID_t	 id;
	Criticality_t	 criticality;
	ANY_t	 value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Field_128P49_t;
typedef struct ProtocolIE_Field_128P50 {
	ProtocolIE_ID_t	 id;
	Criticality_t	 criticality;
	ANY_t	 value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Field_128P50_t;
typedef struct ProtocolIE_Field_128P51 {
	ProtocolIE_ID_t	 id;
	Criticality_t	 criticality;
	ANY_t	 value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Field_128P51_t;
typedef struct ProtocolIE_Field_128P52 {
	ProtocolIE_ID_t	 id;
	Criticality_t	 criticality;
	ANY_t	 value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Field_128P52_t;
typedef struct ProtocolIE_Field_128P53 {
	ProtocolIE_ID_t	 id;
	Criticality_t	 criticality;
	ANY_t	 value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Field_128P53_t;
typedef struct ProtocolIE_Field_128P54 {
	ProtocolIE_ID_t	 id;
	Criticality_t	 criticality;
	ANY_t	 value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Field_128P54_t;
typedef struct ProtocolIE_Field_128P55 {
	ProtocolIE_ID_t	 id;
	Criticality_t	 criticality;
	ANY_t	 value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Field_128P55_t;
typedef struct ProtocolIE_Field_128P56 {
	ProtocolIE_ID_t	 id;
	Criticality_t	 criticality;
	ANY_t	 value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Field_128P56_t;
typedef struct ProtocolIE_Field_128P57 {
	ProtocolIE_ID_t	 id;
	Criticality_t	 criticality;
	ANY_t	 value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Field_128P57_t;
typedef struct ProtocolIE_Field_128P58 {
	ProtocolIE_ID_t	 id;
	Criticality_t	 criticality;
	ANY_t	 value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Field_128P58_t;
typedef struct ProtocolIE_Field_128P59 {
	ProtocolIE_ID_t	 id;
	Criticality_t	 criticality;
	ANY_t	 value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Field_128P59_t;
typedef struct ProtocolIE_Field_128P60 {
	ProtocolIE_ID_t	 id;
	Criticality_t	 criticality;
	ANY_t	 value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Field_128P60_t;
typedef struct ProtocolIE_Field_128P61 {
	ProtocolIE_ID_t	 id;
	Criticality_t	 criticality;
	ANY_t	 value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Field_128P61_t;
typedef struct ProtocolIE_Field_128P62 {
	ProtocolIE_ID_t	 id;
	Criticality_t	 criticality;
	ANY_t	 value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Field_128P62_t;
typedef struct ProtocolIE_Field_128P63 {
	ProtocolIE_ID_t	 id;
	Criticality_t	 criticality;
	ANY_t	 value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Field_128P63_t;
typedef struct ProtocolIE_Field_128P64 {
	ProtocolIE_ID_t	 id;
	Criticality_t	 criticality;
	ANY_t	 value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Field_128P64_t;
typedef struct ProtocolIE_Field_128P65 {
	ProtocolIE_ID_t	 id;
	Criticality_t	 criticality;
	ANY_t	 value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Field_128P65_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Field_128P0;
extern asn_SEQUENCE_specifics_t asn_SPC_ProtocolIE_Field_128P0_specs_1;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Field_128P0_1[3];
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Field_128P1;
extern asn_SEQUENCE_specifics_t asn_SPC_ProtocolIE_Field_128P1_specs_5;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Field_128P1_5[3];
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Field_128P2;
extern asn_SEQUENCE_specifics_t asn_SPC_ProtocolIE_Field_128P2_specs_9;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Field_128P2_9[3];
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Field_128P3;
extern asn_SEQUENCE_specifics_t asn_SPC_ProtocolIE_Field_128P3_specs_13;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Field_128P3_13[3];
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Field_128P4;
extern asn_SEQUENCE_specifics_t asn_SPC_ProtocolIE_Field_128P4_specs_17;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Field_128P4_17[3];
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Field_128P5;
extern asn_SEQUENCE_specifics_t asn_SPC_ProtocolIE_Field_128P5_specs_21;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Field_128P5_21[3];
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Field_128P6;
extern asn_SEQUENCE_specifics_t asn_SPC_ProtocolIE_Field_128P6_specs_25;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Field_128P6_25[3];
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Field_128P7;
extern asn_SEQUENCE_specifics_t asn_SPC_ProtocolIE_Field_128P7_specs_29;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Field_128P7_29[3];
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Field_128P8;
extern asn_SEQUENCE_specifics_t asn_SPC_ProtocolIE_Field_128P8_specs_33;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Field_128P8_33[3];
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Field_128P9;
extern asn_SEQUENCE_specifics_t asn_SPC_ProtocolIE_Field_128P9_specs_37;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Field_128P9_37[3];
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Field_128P10;
extern asn_SEQUENCE_specifics_t asn_SPC_ProtocolIE_Field_128P10_specs_41;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Field_128P10_41[3];
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Field_128P11;
extern asn_SEQUENCE_specifics_t asn_SPC_ProtocolIE_Field_128P11_specs_45;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Field_128P11_45[3];
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Field_128P12;
extern asn_SEQUENCE_specifics_t asn_SPC_ProtocolIE_Field_128P12_specs_49;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Field_128P12_49[3];
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Field_128P13;
extern asn_SEQUENCE_specifics_t asn_SPC_ProtocolIE_Field_128P13_specs_53;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Field_128P13_53[3];
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Field_128P14;
extern asn_SEQUENCE_specifics_t asn_SPC_ProtocolIE_Field_128P14_specs_57;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Field_128P14_57[3];
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Field_128P15;
extern asn_SEQUENCE_specifics_t asn_SPC_ProtocolIE_Field_128P15_specs_61;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Field_128P15_61[3];
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Field_128P16;
extern asn_SEQUENCE_specifics_t asn_SPC_ProtocolIE_Field_128P16_specs_65;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Field_128P16_65[3];
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Field_128P17;
extern asn_SEQUENCE_specifics_t asn_SPC_ProtocolIE_Field_128P17_specs_69;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Field_128P17_69[3];
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Field_128P18;
extern asn_SEQUENCE_specifics_t asn_SPC_ProtocolIE_Field_128P18_specs_73;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Field_128P18_73[3];
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Field_128P19;
extern asn_SEQUENCE_specifics_t asn_SPC_ProtocolIE_Field_128P19_specs_77;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Field_128P19_77[3];
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Field_128P20;
extern asn_SEQUENCE_specifics_t asn_SPC_ProtocolIE_Field_128P20_specs_81;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Field_128P20_81[3];
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Field_128P21;
extern asn_SEQUENCE_specifics_t asn_SPC_ProtocolIE_Field_128P21_specs_85;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Field_128P21_85[3];
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Field_128P22;
extern asn_SEQUENCE_specifics_t asn_SPC_ProtocolIE_Field_128P22_specs_89;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Field_128P22_89[3];
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Field_128P23;
extern asn_SEQUENCE_specifics_t asn_SPC_ProtocolIE_Field_128P23_specs_93;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Field_128P23_93[3];
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Field_128P24;
extern asn_SEQUENCE_specifics_t asn_SPC_ProtocolIE_Field_128P24_specs_97;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Field_128P24_97[3];
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Field_128P25;
extern asn_SEQUENCE_specifics_t asn_SPC_ProtocolIE_Field_128P25_specs_101;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Field_128P25_101[3];
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Field_128P26;
extern asn_SEQUENCE_specifics_t asn_SPC_ProtocolIE_Field_128P26_specs_105;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Field_128P26_105[3];
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Field_128P27;
extern asn_SEQUENCE_specifics_t asn_SPC_ProtocolIE_Field_128P27_specs_109;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Field_128P27_109[3];
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Field_128P28;
extern asn_SEQUENCE_specifics_t asn_SPC_ProtocolIE_Field_128P28_specs_113;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Field_128P28_113[3];
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Field_128P29;
extern asn_SEQUENCE_specifics_t asn_SPC_ProtocolIE_Field_128P29_specs_117;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Field_128P29_117[3];
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Field_128P30;
extern asn_SEQUENCE_specifics_t asn_SPC_ProtocolIE_Field_128P30_specs_121;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Field_128P30_121[3];
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Field_128P31;
extern asn_SEQUENCE_specifics_t asn_SPC_ProtocolIE_Field_128P31_specs_125;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Field_128P31_125[3];
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Field_128P32;
extern asn_SEQUENCE_specifics_t asn_SPC_ProtocolIE_Field_128P32_specs_129;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Field_128P32_129[3];
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Field_128P33;
extern asn_SEQUENCE_specifics_t asn_SPC_ProtocolIE_Field_128P33_specs_133;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Field_128P33_133[3];
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Field_128P34;
extern asn_SEQUENCE_specifics_t asn_SPC_ProtocolIE_Field_128P34_specs_137;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Field_128P34_137[3];
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Field_128P35;
extern asn_SEQUENCE_specifics_t asn_SPC_ProtocolIE_Field_128P35_specs_141;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Field_128P35_141[3];
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Field_128P36;
extern asn_SEQUENCE_specifics_t asn_SPC_ProtocolIE_Field_128P36_specs_145;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Field_128P36_145[3];
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Field_128P37;
extern asn_SEQUENCE_specifics_t asn_SPC_ProtocolIE_Field_128P37_specs_149;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Field_128P37_149[3];
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Field_128P38;
extern asn_SEQUENCE_specifics_t asn_SPC_ProtocolIE_Field_128P38_specs_153;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Field_128P38_153[3];
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Field_128P39;
extern asn_SEQUENCE_specifics_t asn_SPC_ProtocolIE_Field_128P39_specs_157;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Field_128P39_157[3];
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Field_128P40;
extern asn_SEQUENCE_specifics_t asn_SPC_ProtocolIE_Field_128P40_specs_161;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Field_128P40_161[3];
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Field_128P41;
extern asn_SEQUENCE_specifics_t asn_SPC_ProtocolIE_Field_128P41_specs_165;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Field_128P41_165[3];
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Field_128P42;
extern asn_SEQUENCE_specifics_t asn_SPC_ProtocolIE_Field_128P42_specs_169;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Field_128P42_169[3];
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Field_128P43;
extern asn_SEQUENCE_specifics_t asn_SPC_ProtocolIE_Field_128P43_specs_173;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Field_128P43_173[3];
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Field_128P44;
extern asn_SEQUENCE_specifics_t asn_SPC_ProtocolIE_Field_128P44_specs_177;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Field_128P44_177[3];
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Field_128P45;
extern asn_SEQUENCE_specifics_t asn_SPC_ProtocolIE_Field_128P45_specs_181;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Field_128P45_181[3];
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Field_128P46;
extern asn_SEQUENCE_specifics_t asn_SPC_ProtocolIE_Field_128P46_specs_185;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Field_128P46_185[3];
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Field_128P47;
extern asn_SEQUENCE_specifics_t asn_SPC_ProtocolIE_Field_128P47_specs_189;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Field_128P47_189[3];
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Field_128P48;
extern asn_SEQUENCE_specifics_t asn_SPC_ProtocolIE_Field_128P48_specs_193;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Field_128P48_193[3];
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Field_128P49;
extern asn_SEQUENCE_specifics_t asn_SPC_ProtocolIE_Field_128P49_specs_197;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Field_128P49_197[3];
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Field_128P50;
extern asn_SEQUENCE_specifics_t asn_SPC_ProtocolIE_Field_128P50_specs_201;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Field_128P50_201[3];
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Field_128P51;
extern asn_SEQUENCE_specifics_t asn_SPC_ProtocolIE_Field_128P51_specs_205;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Field_128P51_205[3];
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Field_128P52;
extern asn_SEQUENCE_specifics_t asn_SPC_ProtocolIE_Field_128P52_specs_209;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Field_128P52_209[3];
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Field_128P53;
extern asn_SEQUENCE_specifics_t asn_SPC_ProtocolIE_Field_128P53_specs_213;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Field_128P53_213[3];
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Field_128P54;
extern asn_SEQUENCE_specifics_t asn_SPC_ProtocolIE_Field_128P54_specs_217;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Field_128P54_217[3];
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Field_128P55;
extern asn_SEQUENCE_specifics_t asn_SPC_ProtocolIE_Field_128P55_specs_221;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Field_128P55_221[3];
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Field_128P56;
extern asn_SEQUENCE_specifics_t asn_SPC_ProtocolIE_Field_128P56_specs_225;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Field_128P56_225[3];
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Field_128P57;
extern asn_SEQUENCE_specifics_t asn_SPC_ProtocolIE_Field_128P57_specs_229;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Field_128P57_229[3];
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Field_128P58;
extern asn_SEQUENCE_specifics_t asn_SPC_ProtocolIE_Field_128P58_specs_233;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Field_128P58_233[3];
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Field_128P59;
extern asn_SEQUENCE_specifics_t asn_SPC_ProtocolIE_Field_128P59_specs_237;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Field_128P59_237[3];
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Field_128P60;
extern asn_SEQUENCE_specifics_t asn_SPC_ProtocolIE_Field_128P60_specs_241;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Field_128P60_241[3];
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Field_128P61;
extern asn_SEQUENCE_specifics_t asn_SPC_ProtocolIE_Field_128P61_specs_245;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Field_128P61_245[3];
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Field_128P62;
extern asn_SEQUENCE_specifics_t asn_SPC_ProtocolIE_Field_128P62_specs_249;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Field_128P62_249[3];
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Field_128P63;
extern asn_SEQUENCE_specifics_t asn_SPC_ProtocolIE_Field_128P63_specs_253;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Field_128P63_253[3];
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Field_128P64;
extern asn_SEQUENCE_specifics_t asn_SPC_ProtocolIE_Field_128P64_specs_257;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Field_128P64_257[3];
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Field_128P65;
extern asn_SEQUENCE_specifics_t asn_SPC_ProtocolIE_Field_128P65_specs_261;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Field_128P65_261[3];

#ifdef __cplusplus
}
#endif

#endif	/* _ProtocolIE_Field_H_ */
#include <asn_internal.h>
