/*
 * Generated by asn1c-1.0.0 (http://lionet.info/asn1c)
 * From ASN.1 module "S1AP-Containers"
 * 	found in "../asn1/S1AP-Containers.asn"
 * 	`asn1c -gen-PER -fcompound-names -S ../skeletons`
 */

#ifndef	_ProtocolExtensionContainer_H_
#define	_ProtocolExtensionContainer_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ProtocolExtensionField;

/* ProtocolExtensionContainer */
typedef struct ProtocolExtensionContainer_173P0 {
	A_SEQUENCE_OF(struct ProtocolExtensionField) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_173P0_t;
typedef struct ProtocolExtensionContainer_173P1 {
	A_SEQUENCE_OF(struct ProtocolExtensionField) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_173P1_t;
typedef struct ProtocolExtensionContainer_173P2 {
	A_SEQUENCE_OF(struct ProtocolExtensionField) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_173P2_t;
typedef struct ProtocolExtensionContainer_173P3 {
	A_SEQUENCE_OF(struct ProtocolExtensionField) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_173P3_t;
typedef struct ProtocolExtensionContainer_173P4 {
	A_SEQUENCE_OF(struct ProtocolExtensionField) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_173P4_t;
typedef struct ProtocolExtensionContainer_173P5 {
	A_SEQUENCE_OF(struct ProtocolExtensionField) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_173P5_t;
typedef struct ProtocolExtensionContainer_173P6 {
	A_SEQUENCE_OF(struct ProtocolExtensionField) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_173P6_t;
typedef struct ProtocolExtensionContainer_173P7 {
	A_SEQUENCE_OF(struct ProtocolExtensionField) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_173P7_t;
typedef struct ProtocolExtensionContainer_173P8 {
	A_SEQUENCE_OF(struct ProtocolExtensionField) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_173P8_t;
typedef struct ProtocolExtensionContainer_173P9 {
	A_SEQUENCE_OF(struct ProtocolExtensionField) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_173P9_t;
typedef struct ProtocolExtensionContainer_173P10 {
	A_SEQUENCE_OF(struct ProtocolExtensionField) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_173P10_t;
typedef struct ProtocolExtensionContainer_173P11 {
	A_SEQUENCE_OF(struct ProtocolExtensionField) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_173P11_t;
typedef struct ProtocolExtensionContainer_173P12 {
	A_SEQUENCE_OF(struct ProtocolExtensionField) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_173P12_t;
typedef struct ProtocolExtensionContainer_173P13 {
	A_SEQUENCE_OF(struct ProtocolExtensionField) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_173P13_t;
typedef struct ProtocolExtensionContainer_173P14 {
	A_SEQUENCE_OF(struct ProtocolExtensionField) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_173P14_t;
typedef struct ProtocolExtensionContainer_173P15 {
	A_SEQUENCE_OF(struct ProtocolExtensionField) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_173P15_t;
typedef struct ProtocolExtensionContainer_173P16 {
	A_SEQUENCE_OF(struct ProtocolExtensionField) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_173P16_t;
typedef struct ProtocolExtensionContainer_173P17 {
	A_SEQUENCE_OF(struct ProtocolExtensionField) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_173P17_t;
typedef struct ProtocolExtensionContainer_173P18 {
	A_SEQUENCE_OF(struct ProtocolExtensionField) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_173P18_t;
typedef struct ProtocolExtensionContainer_173P19 {
	A_SEQUENCE_OF(struct ProtocolExtensionField) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_173P19_t;
typedef struct ProtocolExtensionContainer_173P20 {
	A_SEQUENCE_OF(struct ProtocolExtensionField) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_173P20_t;
typedef struct ProtocolExtensionContainer_173P21 {
	A_SEQUENCE_OF(struct ProtocolExtensionField) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_173P21_t;
typedef struct ProtocolExtensionContainer_173P22 {
	A_SEQUENCE_OF(struct ProtocolExtensionField) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_173P22_t;
typedef struct ProtocolExtensionContainer_173P23 {
	A_SEQUENCE_OF(struct ProtocolExtensionField) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_173P23_t;
typedef struct ProtocolExtensionContainer_173P24 {
	A_SEQUENCE_OF(struct ProtocolExtensionField) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_173P24_t;
typedef struct ProtocolExtensionContainer_173P25 {
	A_SEQUENCE_OF(struct ProtocolExtensionField) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_173P25_t;
typedef struct ProtocolExtensionContainer_173P26 {
	A_SEQUENCE_OF(struct ProtocolExtensionField) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_173P26_t;
typedef struct ProtocolExtensionContainer_173P27 {
	A_SEQUENCE_OF(struct ProtocolExtensionField) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_173P27_t;
typedef struct ProtocolExtensionContainer_173P28 {
	A_SEQUENCE_OF(struct ProtocolExtensionField) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_173P28_t;
typedef struct ProtocolExtensionContainer_173P29 {
	A_SEQUENCE_OF(struct ProtocolExtensionField) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_173P29_t;
typedef struct ProtocolExtensionContainer_173P30 {
	A_SEQUENCE_OF(struct ProtocolExtensionField) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_173P30_t;
typedef struct ProtocolExtensionContainer_173P31 {
	A_SEQUENCE_OF(struct ProtocolExtensionField) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_173P31_t;
typedef struct ProtocolExtensionContainer_173P32 {
	A_SEQUENCE_OF(struct ProtocolExtensionField) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_173P32_t;
typedef struct ProtocolExtensionContainer_173P33 {
	A_SEQUENCE_OF(struct ProtocolExtensionField) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_173P33_t;
typedef struct ProtocolExtensionContainer_173P34 {
	A_SEQUENCE_OF(struct ProtocolExtensionField) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_173P34_t;
typedef struct ProtocolExtensionContainer_173P35 {
	A_SEQUENCE_OF(struct ProtocolExtensionField) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_173P35_t;
typedef struct ProtocolExtensionContainer_173P36 {
	A_SEQUENCE_OF(struct ProtocolExtensionField) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_173P36_t;
typedef struct ProtocolExtensionContainer_173P37 {
	A_SEQUENCE_OF(struct ProtocolExtensionField) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_173P37_t;
typedef struct ProtocolExtensionContainer_173P38 {
	A_SEQUENCE_OF(struct ProtocolExtensionField) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_173P38_t;
typedef struct ProtocolExtensionContainer_173P39 {
	A_SEQUENCE_OF(struct ProtocolExtensionField) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_173P39_t;
typedef struct ProtocolExtensionContainer_173P40 {
	A_SEQUENCE_OF(struct ProtocolExtensionField) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_173P40_t;
typedef struct ProtocolExtensionContainer_173P41 {
	A_SEQUENCE_OF(struct ProtocolExtensionField) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_173P41_t;
typedef struct ProtocolExtensionContainer_173P42 {
	A_SEQUENCE_OF(struct ProtocolExtensionField) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_173P42_t;
typedef struct ProtocolExtensionContainer_173P43 {
	A_SEQUENCE_OF(struct ProtocolExtensionField) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_173P43_t;
typedef struct ProtocolExtensionContainer_173P44 {
	A_SEQUENCE_OF(struct ProtocolExtensionField) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_173P44_t;
typedef struct ProtocolExtensionContainer_173P45 {
	A_SEQUENCE_OF(struct ProtocolExtensionField) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_173P45_t;
typedef struct ProtocolExtensionContainer_173P46 {
	A_SEQUENCE_OF(struct ProtocolExtensionField) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_173P46_t;
typedef struct ProtocolExtensionContainer_173P47 {
	A_SEQUENCE_OF(struct ProtocolExtensionField) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_173P47_t;
typedef struct ProtocolExtensionContainer_173P48 {
	A_SEQUENCE_OF(struct ProtocolExtensionField) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_173P48_t;
typedef struct ProtocolExtensionContainer_173P49 {
	A_SEQUENCE_OF(struct ProtocolExtensionField) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_173P49_t;
typedef struct ProtocolExtensionContainer_173P50 {
	A_SEQUENCE_OF(struct ProtocolExtensionField) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_173P50_t;
typedef struct ProtocolExtensionContainer_173P51 {
	A_SEQUENCE_OF(struct ProtocolExtensionField) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_173P51_t;
typedef struct ProtocolExtensionContainer_173P52 {
	A_SEQUENCE_OF(struct ProtocolExtensionField) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_173P52_t;
typedef struct ProtocolExtensionContainer_173P53 {
	A_SEQUENCE_OF(struct ProtocolExtensionField) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_173P53_t;
typedef struct ProtocolExtensionContainer_173P54 {
	A_SEQUENCE_OF(struct ProtocolExtensionField) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_173P54_t;
typedef struct ProtocolExtensionContainer_173P55 {
	A_SEQUENCE_OF(struct ProtocolExtensionField) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_173P55_t;
typedef struct ProtocolExtensionContainer_173P56 {
	A_SEQUENCE_OF(struct ProtocolExtensionField) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_173P56_t;
typedef struct ProtocolExtensionContainer_173P57 {
	A_SEQUENCE_OF(struct ProtocolExtensionField) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_173P57_t;
typedef struct ProtocolExtensionContainer_173P58 {
	A_SEQUENCE_OF(struct ProtocolExtensionField) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_173P58_t;
typedef struct ProtocolExtensionContainer_173P59 {
	A_SEQUENCE_OF(struct ProtocolExtensionField) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_173P59_t;
typedef struct ProtocolExtensionContainer_173P60 {
	A_SEQUENCE_OF(struct ProtocolExtensionField) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_173P60_t;
typedef struct ProtocolExtensionContainer_173P61 {
	A_SEQUENCE_OF(struct ProtocolExtensionField) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_173P61_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_173P0;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_173P0_specs_1;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_173P0_1[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_173P0_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_173P1;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_173P1_specs_3;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_173P1_3[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_173P1_constr_3;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_173P2;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_173P2_specs_5;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_173P2_5[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_173P2_constr_5;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_173P3;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_173P3_specs_7;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_173P3_7[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_173P3_constr_7;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_173P4;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_173P4_specs_9;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_173P4_9[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_173P4_constr_9;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_173P5;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_173P5_specs_11;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_173P5_11[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_173P5_constr_11;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_173P6;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_173P6_specs_13;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_173P6_13[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_173P6_constr_13;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_173P7;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_173P7_specs_15;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_173P7_15[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_173P7_constr_15;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_173P8;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_173P8_specs_17;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_173P8_17[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_173P8_constr_17;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_173P9;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_173P9_specs_19;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_173P9_19[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_173P9_constr_19;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_173P10;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_173P10_specs_21;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_173P10_21[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_173P10_constr_21;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_173P11;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_173P11_specs_23;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_173P11_23[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_173P11_constr_23;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_173P12;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_173P12_specs_25;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_173P12_25[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_173P12_constr_25;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_173P13;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_173P13_specs_27;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_173P13_27[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_173P13_constr_27;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_173P14;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_173P14_specs_29;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_173P14_29[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_173P14_constr_29;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_173P15;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_173P15_specs_31;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_173P15_31[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_173P15_constr_31;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_173P16;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_173P16_specs_33;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_173P16_33[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_173P16_constr_33;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_173P17;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_173P17_specs_35;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_173P17_35[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_173P17_constr_35;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_173P18;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_173P18_specs_37;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_173P18_37[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_173P18_constr_37;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_173P19;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_173P19_specs_39;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_173P19_39[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_173P19_constr_39;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_173P20;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_173P20_specs_41;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_173P20_41[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_173P20_constr_41;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_173P21;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_173P21_specs_43;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_173P21_43[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_173P21_constr_43;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_173P22;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_173P22_specs_45;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_173P22_45[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_173P22_constr_45;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_173P23;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_173P23_specs_47;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_173P23_47[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_173P23_constr_47;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_173P24;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_173P24_specs_49;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_173P24_49[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_173P24_constr_49;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_173P25;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_173P25_specs_51;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_173P25_51[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_173P25_constr_51;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_173P26;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_173P26_specs_53;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_173P26_53[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_173P26_constr_53;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_173P27;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_173P27_specs_55;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_173P27_55[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_173P27_constr_55;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_173P28;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_173P28_specs_57;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_173P28_57[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_173P28_constr_57;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_173P29;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_173P29_specs_59;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_173P29_59[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_173P29_constr_59;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_173P30;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_173P30_specs_61;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_173P30_61[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_173P30_constr_61;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_173P31;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_173P31_specs_63;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_173P31_63[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_173P31_constr_63;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_173P32;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_173P32_specs_65;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_173P32_65[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_173P32_constr_65;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_173P33;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_173P33_specs_67;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_173P33_67[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_173P33_constr_67;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_173P34;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_173P34_specs_69;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_173P34_69[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_173P34_constr_69;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_173P35;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_173P35_specs_71;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_173P35_71[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_173P35_constr_71;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_173P36;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_173P36_specs_73;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_173P36_73[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_173P36_constr_73;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_173P37;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_173P37_specs_75;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_173P37_75[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_173P37_constr_75;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_173P38;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_173P38_specs_77;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_173P38_77[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_173P38_constr_77;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_173P39;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_173P39_specs_79;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_173P39_79[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_173P39_constr_79;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_173P40;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_173P40_specs_81;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_173P40_81[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_173P40_constr_81;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_173P41;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_173P41_specs_83;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_173P41_83[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_173P41_constr_83;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_173P42;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_173P42_specs_85;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_173P42_85[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_173P42_constr_85;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_173P43;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_173P43_specs_87;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_173P43_87[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_173P43_constr_87;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_173P44;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_173P44_specs_89;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_173P44_89[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_173P44_constr_89;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_173P45;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_173P45_specs_91;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_173P45_91[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_173P45_constr_91;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_173P46;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_173P46_specs_93;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_173P46_93[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_173P46_constr_93;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_173P47;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_173P47_specs_95;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_173P47_95[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_173P47_constr_95;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_173P48;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_173P48_specs_97;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_173P48_97[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_173P48_constr_97;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_173P49;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_173P49_specs_99;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_173P49_99[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_173P49_constr_99;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_173P50;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_173P50_specs_101;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_173P50_101[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_173P50_constr_101;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_173P51;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_173P51_specs_103;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_173P51_103[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_173P51_constr_103;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_173P52;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_173P52_specs_105;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_173P52_105[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_173P52_constr_105;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_173P53;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_173P53_specs_107;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_173P53_107[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_173P53_constr_107;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_173P54;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_173P54_specs_109;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_173P54_109[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_173P54_constr_109;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_173P55;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_173P55_specs_111;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_173P55_111[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_173P55_constr_111;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_173P56;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_173P56_specs_113;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_173P56_113[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_173P56_constr_113;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_173P57;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_173P57_specs_115;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_173P57_115[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_173P57_constr_115;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_173P58;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_173P58_specs_117;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_173P58_117[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_173P58_constr_117;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_173P59;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_173P59_specs_119;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_173P59_119[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_173P59_constr_119;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_173P60;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_173P60_specs_121;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_173P60_121[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_173P60_constr_121;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_173P61;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_173P61_specs_123;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_173P61_123[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_173P61_constr_123;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ProtocolExtensionField.h"

#endif	/* _ProtocolExtensionContainer_H_ */
#include <asn_internal.h>
