/*
 * Generated by asn1c-1.0.0 (http://lionet.info/asn1c)
 * From ASN.1 module "S1AP-Containers"
 * 	found in "../asn1/S1AP-Containers.asn"
 * 	`asn1c -gen-PER -fcompound-names -S ../skeletons`
 */

#ifndef	_ProtocolExtensionField_H_
#define	_ProtocolExtensionField_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ProtocolExtensionID.h"
#include "Criticality.h"
#include <ANY.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ProtocolExtensionField */
typedef struct ProtocolExtensionField_176P0 {
	ProtocolExtensionID_t	 id;
	Criticality_t	 criticality;
	ANY_t	 extensionValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionField_176P0_t;
typedef struct ProtocolExtensionField_176P1 {
	ProtocolExtensionID_t	 id;
	Criticality_t	 criticality;
	ANY_t	 extensionValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionField_176P1_t;
typedef struct ProtocolExtensionField_176P2 {
	ProtocolExtensionID_t	 id;
	Criticality_t	 criticality;
	ANY_t	 extensionValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionField_176P2_t;
typedef struct ProtocolExtensionField_176P3 {
	ProtocolExtensionID_t	 id;
	Criticality_t	 criticality;
	ANY_t	 extensionValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionField_176P3_t;
typedef struct ProtocolExtensionField_176P4 {
	ProtocolExtensionID_t	 id;
	Criticality_t	 criticality;
	ANY_t	 extensionValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionField_176P4_t;
typedef struct ProtocolExtensionField_176P5 {
	ProtocolExtensionID_t	 id;
	Criticality_t	 criticality;
	ANY_t	 extensionValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionField_176P5_t;
typedef struct ProtocolExtensionField_176P6 {
	ProtocolExtensionID_t	 id;
	Criticality_t	 criticality;
	ANY_t	 extensionValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionField_176P6_t;
typedef struct ProtocolExtensionField_176P7 {
	ProtocolExtensionID_t	 id;
	Criticality_t	 criticality;
	ANY_t	 extensionValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionField_176P7_t;
typedef struct ProtocolExtensionField_176P8 {
	ProtocolExtensionID_t	 id;
	Criticality_t	 criticality;
	ANY_t	 extensionValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionField_176P8_t;
typedef struct ProtocolExtensionField_176P9 {
	ProtocolExtensionID_t	 id;
	Criticality_t	 criticality;
	ANY_t	 extensionValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionField_176P9_t;
typedef struct ProtocolExtensionField_176P10 {
	ProtocolExtensionID_t	 id;
	Criticality_t	 criticality;
	ANY_t	 extensionValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionField_176P10_t;
typedef struct ProtocolExtensionField_176P11 {
	ProtocolExtensionID_t	 id;
	Criticality_t	 criticality;
	ANY_t	 extensionValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionField_176P11_t;
typedef struct ProtocolExtensionField_176P12 {
	ProtocolExtensionID_t	 id;
	Criticality_t	 criticality;
	ANY_t	 extensionValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionField_176P12_t;
typedef struct ProtocolExtensionField_176P13 {
	ProtocolExtensionID_t	 id;
	Criticality_t	 criticality;
	ANY_t	 extensionValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionField_176P13_t;
typedef struct ProtocolExtensionField_176P14 {
	ProtocolExtensionID_t	 id;
	Criticality_t	 criticality;
	ANY_t	 extensionValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionField_176P14_t;
typedef struct ProtocolExtensionField_176P15 {
	ProtocolExtensionID_t	 id;
	Criticality_t	 criticality;
	ANY_t	 extensionValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionField_176P15_t;
typedef struct ProtocolExtensionField_176P16 {
	ProtocolExtensionID_t	 id;
	Criticality_t	 criticality;
	ANY_t	 extensionValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionField_176P16_t;
typedef struct ProtocolExtensionField_176P17 {
	ProtocolExtensionID_t	 id;
	Criticality_t	 criticality;
	ANY_t	 extensionValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionField_176P17_t;
typedef struct ProtocolExtensionField_176P18 {
	ProtocolExtensionID_t	 id;
	Criticality_t	 criticality;
	ANY_t	 extensionValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionField_176P18_t;
typedef struct ProtocolExtensionField_176P19 {
	ProtocolExtensionID_t	 id;
	Criticality_t	 criticality;
	ANY_t	 extensionValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionField_176P19_t;
typedef struct ProtocolExtensionField_176P20 {
	ProtocolExtensionID_t	 id;
	Criticality_t	 criticality;
	ANY_t	 extensionValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionField_176P20_t;
typedef struct ProtocolExtensionField_176P21 {
	ProtocolExtensionID_t	 id;
	Criticality_t	 criticality;
	ANY_t	 extensionValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionField_176P21_t;
typedef struct ProtocolExtensionField_176P22 {
	ProtocolExtensionID_t	 id;
	Criticality_t	 criticality;
	ANY_t	 extensionValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionField_176P22_t;
typedef struct ProtocolExtensionField_176P23 {
	ProtocolExtensionID_t	 id;
	Criticality_t	 criticality;
	ANY_t	 extensionValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionField_176P23_t;
typedef struct ProtocolExtensionField_176P24 {
	ProtocolExtensionID_t	 id;
	Criticality_t	 criticality;
	ANY_t	 extensionValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionField_176P24_t;
typedef struct ProtocolExtensionField_176P25 {
	ProtocolExtensionID_t	 id;
	Criticality_t	 criticality;
	ANY_t	 extensionValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionField_176P25_t;
typedef struct ProtocolExtensionField_176P26 {
	ProtocolExtensionID_t	 id;
	Criticality_t	 criticality;
	ANY_t	 extensionValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionField_176P26_t;
typedef struct ProtocolExtensionField_176P27 {
	ProtocolExtensionID_t	 id;
	Criticality_t	 criticality;
	ANY_t	 extensionValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionField_176P27_t;
typedef struct ProtocolExtensionField_176P28 {
	ProtocolExtensionID_t	 id;
	Criticality_t	 criticality;
	ANY_t	 extensionValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionField_176P28_t;
typedef struct ProtocolExtensionField_176P29 {
	ProtocolExtensionID_t	 id;
	Criticality_t	 criticality;
	ANY_t	 extensionValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionField_176P29_t;
typedef struct ProtocolExtensionField_176P30 {
	ProtocolExtensionID_t	 id;
	Criticality_t	 criticality;
	ANY_t	 extensionValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionField_176P30_t;
typedef struct ProtocolExtensionField_176P31 {
	ProtocolExtensionID_t	 id;
	Criticality_t	 criticality;
	ANY_t	 extensionValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionField_176P31_t;
typedef struct ProtocolExtensionField_176P32 {
	ProtocolExtensionID_t	 id;
	Criticality_t	 criticality;
	ANY_t	 extensionValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionField_176P32_t;
typedef struct ProtocolExtensionField_176P33 {
	ProtocolExtensionID_t	 id;
	Criticality_t	 criticality;
	ANY_t	 extensionValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionField_176P33_t;
typedef struct ProtocolExtensionField_176P34 {
	ProtocolExtensionID_t	 id;
	Criticality_t	 criticality;
	ANY_t	 extensionValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionField_176P34_t;
typedef struct ProtocolExtensionField_176P35 {
	ProtocolExtensionID_t	 id;
	Criticality_t	 criticality;
	ANY_t	 extensionValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionField_176P35_t;
typedef struct ProtocolExtensionField_176P36 {
	ProtocolExtensionID_t	 id;
	Criticality_t	 criticality;
	ANY_t	 extensionValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionField_176P36_t;
typedef struct ProtocolExtensionField_176P37 {
	ProtocolExtensionID_t	 id;
	Criticality_t	 criticality;
	ANY_t	 extensionValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionField_176P37_t;
typedef struct ProtocolExtensionField_176P38 {
	ProtocolExtensionID_t	 id;
	Criticality_t	 criticality;
	ANY_t	 extensionValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionField_176P38_t;
typedef struct ProtocolExtensionField_176P39 {
	ProtocolExtensionID_t	 id;
	Criticality_t	 criticality;
	ANY_t	 extensionValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionField_176P39_t;
typedef struct ProtocolExtensionField_176P40 {
	ProtocolExtensionID_t	 id;
	Criticality_t	 criticality;
	ANY_t	 extensionValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionField_176P40_t;
typedef struct ProtocolExtensionField_176P41 {
	ProtocolExtensionID_t	 id;
	Criticality_t	 criticality;
	ANY_t	 extensionValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionField_176P41_t;
typedef struct ProtocolExtensionField_176P42 {
	ProtocolExtensionID_t	 id;
	Criticality_t	 criticality;
	ANY_t	 extensionValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionField_176P42_t;
typedef struct ProtocolExtensionField_176P43 {
	ProtocolExtensionID_t	 id;
	Criticality_t	 criticality;
	ANY_t	 extensionValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionField_176P43_t;
typedef struct ProtocolExtensionField_176P44 {
	ProtocolExtensionID_t	 id;
	Criticality_t	 criticality;
	ANY_t	 extensionValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionField_176P44_t;
typedef struct ProtocolExtensionField_176P45 {
	ProtocolExtensionID_t	 id;
	Criticality_t	 criticality;
	ANY_t	 extensionValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionField_176P45_t;
typedef struct ProtocolExtensionField_176P46 {
	ProtocolExtensionID_t	 id;
	Criticality_t	 criticality;
	ANY_t	 extensionValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionField_176P46_t;
typedef struct ProtocolExtensionField_176P47 {
	ProtocolExtensionID_t	 id;
	Criticality_t	 criticality;
	ANY_t	 extensionValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionField_176P47_t;
typedef struct ProtocolExtensionField_176P48 {
	ProtocolExtensionID_t	 id;
	Criticality_t	 criticality;
	ANY_t	 extensionValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionField_176P48_t;
typedef struct ProtocolExtensionField_176P49 {
	ProtocolExtensionID_t	 id;
	Criticality_t	 criticality;
	ANY_t	 extensionValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionField_176P49_t;
typedef struct ProtocolExtensionField_176P50 {
	ProtocolExtensionID_t	 id;
	Criticality_t	 criticality;
	ANY_t	 extensionValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionField_176P50_t;
typedef struct ProtocolExtensionField_176P51 {
	ProtocolExtensionID_t	 id;
	Criticality_t	 criticality;
	ANY_t	 extensionValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionField_176P51_t;
typedef struct ProtocolExtensionField_176P52 {
	ProtocolExtensionID_t	 id;
	Criticality_t	 criticality;
	ANY_t	 extensionValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionField_176P52_t;
typedef struct ProtocolExtensionField_176P53 {
	ProtocolExtensionID_t	 id;
	Criticality_t	 criticality;
	ANY_t	 extensionValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionField_176P53_t;
typedef struct ProtocolExtensionField_176P54 {
	ProtocolExtensionID_t	 id;
	Criticality_t	 criticality;
	ANY_t	 extensionValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionField_176P54_t;
typedef struct ProtocolExtensionField_176P55 {
	ProtocolExtensionID_t	 id;
	Criticality_t	 criticality;
	ANY_t	 extensionValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionField_176P55_t;
typedef struct ProtocolExtensionField_176P56 {
	ProtocolExtensionID_t	 id;
	Criticality_t	 criticality;
	ANY_t	 extensionValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionField_176P56_t;
typedef struct ProtocolExtensionField_176P57 {
	ProtocolExtensionID_t	 id;
	Criticality_t	 criticality;
	ANY_t	 extensionValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionField_176P57_t;
typedef struct ProtocolExtensionField_176P58 {
	ProtocolExtensionID_t	 id;
	Criticality_t	 criticality;
	ANY_t	 extensionValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionField_176P58_t;
typedef struct ProtocolExtensionField_176P59 {
	ProtocolExtensionID_t	 id;
	Criticality_t	 criticality;
	ANY_t	 extensionValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionField_176P59_t;
typedef struct ProtocolExtensionField_176P60 {
	ProtocolExtensionID_t	 id;
	Criticality_t	 criticality;
	ANY_t	 extensionValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionField_176P60_t;
typedef struct ProtocolExtensionField_176P61 {
	ProtocolExtensionID_t	 id;
	Criticality_t	 criticality;
	ANY_t	 extensionValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionField_176P61_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionField_176P0;
extern asn_SEQUENCE_specifics_t asn_SPC_ProtocolExtensionField_176P0_specs_1;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionField_176P0_1[3];
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionField_176P1;
extern asn_SEQUENCE_specifics_t asn_SPC_ProtocolExtensionField_176P1_specs_5;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionField_176P1_5[3];
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionField_176P2;
extern asn_SEQUENCE_specifics_t asn_SPC_ProtocolExtensionField_176P2_specs_9;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionField_176P2_9[3];
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionField_176P3;
extern asn_SEQUENCE_specifics_t asn_SPC_ProtocolExtensionField_176P3_specs_13;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionField_176P3_13[3];
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionField_176P4;
extern asn_SEQUENCE_specifics_t asn_SPC_ProtocolExtensionField_176P4_specs_17;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionField_176P4_17[3];
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionField_176P5;
extern asn_SEQUENCE_specifics_t asn_SPC_ProtocolExtensionField_176P5_specs_21;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionField_176P5_21[3];
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionField_176P6;
extern asn_SEQUENCE_specifics_t asn_SPC_ProtocolExtensionField_176P6_specs_25;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionField_176P6_25[3];
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionField_176P7;
extern asn_SEQUENCE_specifics_t asn_SPC_ProtocolExtensionField_176P7_specs_29;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionField_176P7_29[3];
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionField_176P8;
extern asn_SEQUENCE_specifics_t asn_SPC_ProtocolExtensionField_176P8_specs_33;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionField_176P8_33[3];
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionField_176P9;
extern asn_SEQUENCE_specifics_t asn_SPC_ProtocolExtensionField_176P9_specs_37;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionField_176P9_37[3];
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionField_176P10;
extern asn_SEQUENCE_specifics_t asn_SPC_ProtocolExtensionField_176P10_specs_41;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionField_176P10_41[3];
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionField_176P11;
extern asn_SEQUENCE_specifics_t asn_SPC_ProtocolExtensionField_176P11_specs_45;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionField_176P11_45[3];
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionField_176P12;
extern asn_SEQUENCE_specifics_t asn_SPC_ProtocolExtensionField_176P12_specs_49;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionField_176P12_49[3];
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionField_176P13;
extern asn_SEQUENCE_specifics_t asn_SPC_ProtocolExtensionField_176P13_specs_53;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionField_176P13_53[3];
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionField_176P14;
extern asn_SEQUENCE_specifics_t asn_SPC_ProtocolExtensionField_176P14_specs_57;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionField_176P14_57[3];
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionField_176P15;
extern asn_SEQUENCE_specifics_t asn_SPC_ProtocolExtensionField_176P15_specs_61;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionField_176P15_61[3];
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionField_176P16;
extern asn_SEQUENCE_specifics_t asn_SPC_ProtocolExtensionField_176P16_specs_65;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionField_176P16_65[3];
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionField_176P17;
extern asn_SEQUENCE_specifics_t asn_SPC_ProtocolExtensionField_176P17_specs_69;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionField_176P17_69[3];
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionField_176P18;
extern asn_SEQUENCE_specifics_t asn_SPC_ProtocolExtensionField_176P18_specs_73;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionField_176P18_73[3];
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionField_176P19;
extern asn_SEQUENCE_specifics_t asn_SPC_ProtocolExtensionField_176P19_specs_77;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionField_176P19_77[3];
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionField_176P20;
extern asn_SEQUENCE_specifics_t asn_SPC_ProtocolExtensionField_176P20_specs_81;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionField_176P20_81[3];
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionField_176P21;
extern asn_SEQUENCE_specifics_t asn_SPC_ProtocolExtensionField_176P21_specs_85;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionField_176P21_85[3];
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionField_176P22;
extern asn_SEQUENCE_specifics_t asn_SPC_ProtocolExtensionField_176P22_specs_89;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionField_176P22_89[3];
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionField_176P23;
extern asn_SEQUENCE_specifics_t asn_SPC_ProtocolExtensionField_176P23_specs_93;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionField_176P23_93[3];
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionField_176P24;
extern asn_SEQUENCE_specifics_t asn_SPC_ProtocolExtensionField_176P24_specs_97;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionField_176P24_97[3];
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionField_176P25;
extern asn_SEQUENCE_specifics_t asn_SPC_ProtocolExtensionField_176P25_specs_101;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionField_176P25_101[3];
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionField_176P26;
extern asn_SEQUENCE_specifics_t asn_SPC_ProtocolExtensionField_176P26_specs_105;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionField_176P26_105[3];
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionField_176P27;
extern asn_SEQUENCE_specifics_t asn_SPC_ProtocolExtensionField_176P27_specs_109;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionField_176P27_109[3];
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionField_176P28;
extern asn_SEQUENCE_specifics_t asn_SPC_ProtocolExtensionField_176P28_specs_113;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionField_176P28_113[3];
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionField_176P29;
extern asn_SEQUENCE_specifics_t asn_SPC_ProtocolExtensionField_176P29_specs_117;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionField_176P29_117[3];
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionField_176P30;
extern asn_SEQUENCE_specifics_t asn_SPC_ProtocolExtensionField_176P30_specs_121;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionField_176P30_121[3];
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionField_176P31;
extern asn_SEQUENCE_specifics_t asn_SPC_ProtocolExtensionField_176P31_specs_125;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionField_176P31_125[3];
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionField_176P32;
extern asn_SEQUENCE_specifics_t asn_SPC_ProtocolExtensionField_176P32_specs_129;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionField_176P32_129[3];
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionField_176P33;
extern asn_SEQUENCE_specifics_t asn_SPC_ProtocolExtensionField_176P33_specs_133;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionField_176P33_133[3];
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionField_176P34;
extern asn_SEQUENCE_specifics_t asn_SPC_ProtocolExtensionField_176P34_specs_137;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionField_176P34_137[3];
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionField_176P35;
extern asn_SEQUENCE_specifics_t asn_SPC_ProtocolExtensionField_176P35_specs_141;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionField_176P35_141[3];
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionField_176P36;
extern asn_SEQUENCE_specifics_t asn_SPC_ProtocolExtensionField_176P36_specs_145;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionField_176P36_145[3];
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionField_176P37;
extern asn_SEQUENCE_specifics_t asn_SPC_ProtocolExtensionField_176P37_specs_149;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionField_176P37_149[3];
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionField_176P38;
extern asn_SEQUENCE_specifics_t asn_SPC_ProtocolExtensionField_176P38_specs_153;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionField_176P38_153[3];
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionField_176P39;
extern asn_SEQUENCE_specifics_t asn_SPC_ProtocolExtensionField_176P39_specs_157;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionField_176P39_157[3];
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionField_176P40;
extern asn_SEQUENCE_specifics_t asn_SPC_ProtocolExtensionField_176P40_specs_161;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionField_176P40_161[3];
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionField_176P41;
extern asn_SEQUENCE_specifics_t asn_SPC_ProtocolExtensionField_176P41_specs_165;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionField_176P41_165[3];
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionField_176P42;
extern asn_SEQUENCE_specifics_t asn_SPC_ProtocolExtensionField_176P42_specs_169;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionField_176P42_169[3];
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionField_176P43;
extern asn_SEQUENCE_specifics_t asn_SPC_ProtocolExtensionField_176P43_specs_173;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionField_176P43_173[3];
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionField_176P44;
extern asn_SEQUENCE_specifics_t asn_SPC_ProtocolExtensionField_176P44_specs_177;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionField_176P44_177[3];
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionField_176P45;
extern asn_SEQUENCE_specifics_t asn_SPC_ProtocolExtensionField_176P45_specs_181;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionField_176P45_181[3];
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionField_176P46;
extern asn_SEQUENCE_specifics_t asn_SPC_ProtocolExtensionField_176P46_specs_185;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionField_176P46_185[3];
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionField_176P47;
extern asn_SEQUENCE_specifics_t asn_SPC_ProtocolExtensionField_176P47_specs_189;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionField_176P47_189[3];
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionField_176P48;
extern asn_SEQUENCE_specifics_t asn_SPC_ProtocolExtensionField_176P48_specs_193;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionField_176P48_193[3];
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionField_176P49;
extern asn_SEQUENCE_specifics_t asn_SPC_ProtocolExtensionField_176P49_specs_197;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionField_176P49_197[3];
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionField_176P50;
extern asn_SEQUENCE_specifics_t asn_SPC_ProtocolExtensionField_176P50_specs_201;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionField_176P50_201[3];
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionField_176P51;
extern asn_SEQUENCE_specifics_t asn_SPC_ProtocolExtensionField_176P51_specs_205;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionField_176P51_205[3];
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionField_176P52;
extern asn_SEQUENCE_specifics_t asn_SPC_ProtocolExtensionField_176P52_specs_209;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionField_176P52_209[3];
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionField_176P53;
extern asn_SEQUENCE_specifics_t asn_SPC_ProtocolExtensionField_176P53_specs_213;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionField_176P53_213[3];
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionField_176P54;
extern asn_SEQUENCE_specifics_t asn_SPC_ProtocolExtensionField_176P54_specs_217;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionField_176P54_217[3];
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionField_176P55;
extern asn_SEQUENCE_specifics_t asn_SPC_ProtocolExtensionField_176P55_specs_221;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionField_176P55_221[3];
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionField_176P56;
extern asn_SEQUENCE_specifics_t asn_SPC_ProtocolExtensionField_176P56_specs_225;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionField_176P56_225[3];
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionField_176P57;
extern asn_SEQUENCE_specifics_t asn_SPC_ProtocolExtensionField_176P57_specs_229;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionField_176P57_229[3];
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionField_176P58;
extern asn_SEQUENCE_specifics_t asn_SPC_ProtocolExtensionField_176P58_specs_233;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionField_176P58_233[3];
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionField_176P59;
extern asn_SEQUENCE_specifics_t asn_SPC_ProtocolExtensionField_176P59_specs_237;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionField_176P59_237[3];
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionField_176P60;
extern asn_SEQUENCE_specifics_t asn_SPC_ProtocolExtensionField_176P60_specs_241;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionField_176P60_241[3];
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionField_176P61;
extern asn_SEQUENCE_specifics_t asn_SPC_ProtocolExtensionField_176P61_specs_245;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionField_176P61_245[3];

#ifdef __cplusplus
}
#endif

#endif	/* _ProtocolExtensionField_H_ */
#include <asn_internal.h>
