/*
 * Generated by asn1c-1.0.0 (http://lionet.info/asn1c)
 * From ASN.1 module "S1AP-Containers"
 * 	found in "../asn1/S1AP-Containers.asn"
 * 	`asn1c -gen-PER -fcompound-names -S ../skeletons`
 */

#include "ProtocolIE-FieldPair.h"

