/*
 * Generated by asn1c-1.0.0 (http://lionet.info/asn1c)
 * From ASN.1 module "S1AP-Containers"
 * 	found in "../asn1/S1AP-Containers.asn"
 * 	`asn1c -gen-PER -fcompound-names -S ../skeletons`
 */

#ifndef	_ProtocolIE_Container_H_
#define	_ProtocolIE_Container_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ProtocolIE_Field;

/* ProtocolIE-Container */
typedef struct ProtocolIE_Container_122P0 {
	A_SEQUENCE_OF(struct ProtocolIE_Field) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_122P0_t;
typedef struct ProtocolIE_Container_122P1 {
	A_SEQUENCE_OF(struct ProtocolIE_Field) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_122P1_t;
typedef struct ProtocolIE_Container_122P2 {
	A_SEQUENCE_OF(struct ProtocolIE_Field) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_122P2_t;
typedef struct ProtocolIE_Container_122P3 {
	A_SEQUENCE_OF(struct ProtocolIE_Field) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_122P3_t;
typedef struct ProtocolIE_Container_122P4 {
	A_SEQUENCE_OF(struct ProtocolIE_Field) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_122P4_t;
typedef struct ProtocolIE_Container_122P5 {
	A_SEQUENCE_OF(struct ProtocolIE_Field) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_122P5_t;
typedef struct ProtocolIE_Container_122P6 {
	A_SEQUENCE_OF(struct ProtocolIE_Field) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_122P6_t;
typedef struct ProtocolIE_Container_122P7 {
	A_SEQUENCE_OF(struct ProtocolIE_Field) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_122P7_t;
typedef struct ProtocolIE_Container_122P8 {
	A_SEQUENCE_OF(struct ProtocolIE_Field) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_122P8_t;
typedef struct ProtocolIE_Container_122P9 {
	A_SEQUENCE_OF(struct ProtocolIE_Field) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_122P9_t;
typedef struct ProtocolIE_Container_122P10 {
	A_SEQUENCE_OF(struct ProtocolIE_Field) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_122P10_t;
typedef struct ProtocolIE_Container_122P11 {
	A_SEQUENCE_OF(struct ProtocolIE_Field) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_122P11_t;
typedef struct ProtocolIE_Container_122P12 {
	A_SEQUENCE_OF(struct ProtocolIE_Field) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_122P12_t;
typedef struct ProtocolIE_Container_122P13 {
	A_SEQUENCE_OF(struct ProtocolIE_Field) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_122P13_t;
typedef struct ProtocolIE_Container_122P14 {
	A_SEQUENCE_OF(struct ProtocolIE_Field) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_122P14_t;
typedef struct ProtocolIE_Container_122P15 {
	A_SEQUENCE_OF(struct ProtocolIE_Field) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_122P15_t;
typedef struct ProtocolIE_Container_122P16 {
	A_SEQUENCE_OF(struct ProtocolIE_Field) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_122P16_t;
typedef struct ProtocolIE_Container_122P17 {
	A_SEQUENCE_OF(struct ProtocolIE_Field) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_122P17_t;
typedef struct ProtocolIE_Container_122P18 {
	A_SEQUENCE_OF(struct ProtocolIE_Field) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_122P18_t;
typedef struct ProtocolIE_Container_122P19 {
	A_SEQUENCE_OF(struct ProtocolIE_Field) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_122P19_t;
typedef struct ProtocolIE_Container_122P20 {
	A_SEQUENCE_OF(struct ProtocolIE_Field) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_122P20_t;
typedef struct ProtocolIE_Container_122P21 {
	A_SEQUENCE_OF(struct ProtocolIE_Field) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_122P21_t;
typedef struct ProtocolIE_Container_122P22 {
	A_SEQUENCE_OF(struct ProtocolIE_Field) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_122P22_t;
typedef struct ProtocolIE_Container_122P23 {
	A_SEQUENCE_OF(struct ProtocolIE_Field) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_122P23_t;
typedef struct ProtocolIE_Container_122P24 {
	A_SEQUENCE_OF(struct ProtocolIE_Field) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_122P24_t;
typedef struct ProtocolIE_Container_122P25 {
	A_SEQUENCE_OF(struct ProtocolIE_Field) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_122P25_t;
typedef struct ProtocolIE_Container_122P26 {
	A_SEQUENCE_OF(struct ProtocolIE_Field) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_122P26_t;
typedef struct ProtocolIE_Container_122P27 {
	A_SEQUENCE_OF(struct ProtocolIE_Field) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_122P27_t;
typedef struct ProtocolIE_Container_122P28 {
	A_SEQUENCE_OF(struct ProtocolIE_Field) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_122P28_t;
typedef struct ProtocolIE_Container_122P29 {
	A_SEQUENCE_OF(struct ProtocolIE_Field) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_122P29_t;
typedef struct ProtocolIE_Container_122P30 {
	A_SEQUENCE_OF(struct ProtocolIE_Field) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_122P30_t;
typedef struct ProtocolIE_Container_122P31 {
	A_SEQUENCE_OF(struct ProtocolIE_Field) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_122P31_t;
typedef struct ProtocolIE_Container_122P32 {
	A_SEQUENCE_OF(struct ProtocolIE_Field) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_122P32_t;
typedef struct ProtocolIE_Container_122P33 {
	A_SEQUENCE_OF(struct ProtocolIE_Field) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_122P33_t;
typedef struct ProtocolIE_Container_122P34 {
	A_SEQUENCE_OF(struct ProtocolIE_Field) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_122P34_t;
typedef struct ProtocolIE_Container_122P35 {
	A_SEQUENCE_OF(struct ProtocolIE_Field) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_122P35_t;
typedef struct ProtocolIE_Container_122P36 {
	A_SEQUENCE_OF(struct ProtocolIE_Field) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_122P36_t;
typedef struct ProtocolIE_Container_122P37 {
	A_SEQUENCE_OF(struct ProtocolIE_Field) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_122P37_t;
typedef struct ProtocolIE_Container_122P38 {
	A_SEQUENCE_OF(struct ProtocolIE_Field) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_122P38_t;
typedef struct ProtocolIE_Container_122P39 {
	A_SEQUENCE_OF(struct ProtocolIE_Field) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_122P39_t;
typedef struct ProtocolIE_Container_122P40 {
	A_SEQUENCE_OF(struct ProtocolIE_Field) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_122P40_t;
typedef struct ProtocolIE_Container_122P41 {
	A_SEQUENCE_OF(struct ProtocolIE_Field) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_122P41_t;
typedef struct ProtocolIE_Container_122P42 {
	A_SEQUENCE_OF(struct ProtocolIE_Field) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_122P42_t;
typedef struct ProtocolIE_Container_122P43 {
	A_SEQUENCE_OF(struct ProtocolIE_Field) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_122P43_t;
typedef struct ProtocolIE_Container_122P44 {
	A_SEQUENCE_OF(struct ProtocolIE_Field) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_122P44_t;
typedef struct ProtocolIE_Container_122P45 {
	A_SEQUENCE_OF(struct ProtocolIE_Field) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_122P45_t;
typedef struct ProtocolIE_Container_122P46 {
	A_SEQUENCE_OF(struct ProtocolIE_Field) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_122P46_t;
typedef struct ProtocolIE_Container_122P47 {
	A_SEQUENCE_OF(struct ProtocolIE_Field) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_122P47_t;
typedef struct ProtocolIE_Container_122P48 {
	A_SEQUENCE_OF(struct ProtocolIE_Field) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_122P48_t;
typedef struct ProtocolIE_Container_122P49 {
	A_SEQUENCE_OF(struct ProtocolIE_Field) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_122P49_t;
typedef struct ProtocolIE_Container_122P50 {
	A_SEQUENCE_OF(struct ProtocolIE_Field) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_122P50_t;
typedef struct ProtocolIE_Container_122P51 {
	A_SEQUENCE_OF(struct ProtocolIE_Field) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_122P51_t;
typedef struct ProtocolIE_Container_122P52 {
	A_SEQUENCE_OF(struct ProtocolIE_Field) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_122P52_t;
typedef struct ProtocolIE_Container_122P53 {
	A_SEQUENCE_OF(struct ProtocolIE_Field) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_122P53_t;
typedef struct ProtocolIE_Container_122P54 {
	A_SEQUENCE_OF(struct ProtocolIE_Field) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_122P54_t;
typedef struct ProtocolIE_Container_122P55 {
	A_SEQUENCE_OF(struct ProtocolIE_Field) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_122P55_t;
typedef struct ProtocolIE_Container_122P56 {
	A_SEQUENCE_OF(struct ProtocolIE_Field) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_122P56_t;
typedef struct ProtocolIE_Container_122P57 {
	A_SEQUENCE_OF(struct ProtocolIE_Field) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_122P57_t;
typedef struct ProtocolIE_Container_122P58 {
	A_SEQUENCE_OF(struct ProtocolIE_Field) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_122P58_t;
typedef struct ProtocolIE_Container_122P59 {
	A_SEQUENCE_OF(struct ProtocolIE_Field) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_122P59_t;
typedef struct ProtocolIE_Container_122P60 {
	A_SEQUENCE_OF(struct ProtocolIE_Field) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_122P60_t;
typedef struct ProtocolIE_Container_122P61 {
	A_SEQUENCE_OF(struct ProtocolIE_Field) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_122P61_t;
typedef struct ProtocolIE_Container_122P62 {
	A_SEQUENCE_OF(struct ProtocolIE_Field) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_122P62_t;
typedef struct ProtocolIE_Container_122P63 {
	A_SEQUENCE_OF(struct ProtocolIE_Field) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_122P63_t;
typedef struct ProtocolIE_Container_122P64 {
	A_SEQUENCE_OF(struct ProtocolIE_Field) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_122P64_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_122P0;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_122P0_specs_1;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_122P0_1[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_122P0_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_122P1;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_122P1_specs_3;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_122P1_3[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_122P1_constr_3;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_122P2;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_122P2_specs_5;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_122P2_5[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_122P2_constr_5;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_122P3;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_122P3_specs_7;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_122P3_7[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_122P3_constr_7;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_122P4;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_122P4_specs_9;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_122P4_9[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_122P4_constr_9;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_122P5;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_122P5_specs_11;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_122P5_11[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_122P5_constr_11;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_122P6;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_122P6_specs_13;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_122P6_13[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_122P6_constr_13;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_122P7;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_122P7_specs_15;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_122P7_15[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_122P7_constr_15;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_122P8;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_122P8_specs_17;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_122P8_17[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_122P8_constr_17;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_122P9;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_122P9_specs_19;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_122P9_19[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_122P9_constr_19;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_122P10;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_122P10_specs_21;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_122P10_21[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_122P10_constr_21;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_122P11;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_122P11_specs_23;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_122P11_23[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_122P11_constr_23;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_122P12;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_122P12_specs_25;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_122P12_25[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_122P12_constr_25;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_122P13;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_122P13_specs_27;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_122P13_27[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_122P13_constr_27;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_122P14;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_122P14_specs_29;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_122P14_29[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_122P14_constr_29;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_122P15;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_122P15_specs_31;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_122P15_31[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_122P15_constr_31;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_122P16;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_122P16_specs_33;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_122P16_33[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_122P16_constr_33;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_122P17;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_122P17_specs_35;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_122P17_35[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_122P17_constr_35;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_122P18;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_122P18_specs_37;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_122P18_37[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_122P18_constr_37;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_122P19;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_122P19_specs_39;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_122P19_39[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_122P19_constr_39;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_122P20;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_122P20_specs_41;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_122P20_41[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_122P20_constr_41;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_122P21;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_122P21_specs_43;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_122P21_43[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_122P21_constr_43;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_122P22;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_122P22_specs_45;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_122P22_45[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_122P22_constr_45;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_122P23;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_122P23_specs_47;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_122P23_47[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_122P23_constr_47;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_122P24;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_122P24_specs_49;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_122P24_49[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_122P24_constr_49;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_122P25;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_122P25_specs_51;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_122P25_51[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_122P25_constr_51;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_122P26;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_122P26_specs_53;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_122P26_53[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_122P26_constr_53;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_122P27;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_122P27_specs_55;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_122P27_55[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_122P27_constr_55;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_122P28;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_122P28_specs_57;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_122P28_57[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_122P28_constr_57;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_122P29;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_122P29_specs_59;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_122P29_59[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_122P29_constr_59;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_122P30;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_122P30_specs_61;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_122P30_61[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_122P30_constr_61;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_122P31;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_122P31_specs_63;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_122P31_63[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_122P31_constr_63;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_122P32;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_122P32_specs_65;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_122P32_65[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_122P32_constr_65;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_122P33;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_122P33_specs_67;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_122P33_67[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_122P33_constr_67;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_122P34;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_122P34_specs_69;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_122P34_69[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_122P34_constr_69;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_122P35;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_122P35_specs_71;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_122P35_71[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_122P35_constr_71;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_122P36;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_122P36_specs_73;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_122P36_73[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_122P36_constr_73;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_122P37;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_122P37_specs_75;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_122P37_75[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_122P37_constr_75;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_122P38;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_122P38_specs_77;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_122P38_77[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_122P38_constr_77;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_122P39;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_122P39_specs_79;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_122P39_79[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_122P39_constr_79;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_122P40;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_122P40_specs_81;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_122P40_81[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_122P40_constr_81;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_122P41;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_122P41_specs_83;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_122P41_83[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_122P41_constr_83;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_122P42;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_122P42_specs_85;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_122P42_85[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_122P42_constr_85;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_122P43;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_122P43_specs_87;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_122P43_87[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_122P43_constr_87;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_122P44;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_122P44_specs_89;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_122P44_89[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_122P44_constr_89;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_122P45;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_122P45_specs_91;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_122P45_91[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_122P45_constr_91;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_122P46;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_122P46_specs_93;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_122P46_93[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_122P46_constr_93;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_122P47;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_122P47_specs_95;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_122P47_95[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_122P47_constr_95;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_122P48;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_122P48_specs_97;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_122P48_97[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_122P48_constr_97;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_122P49;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_122P49_specs_99;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_122P49_99[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_122P49_constr_99;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_122P50;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_122P50_specs_101;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_122P50_101[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_122P50_constr_101;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_122P51;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_122P51_specs_103;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_122P51_103[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_122P51_constr_103;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_122P52;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_122P52_specs_105;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_122P52_105[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_122P52_constr_105;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_122P53;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_122P53_specs_107;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_122P53_107[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_122P53_constr_107;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_122P54;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_122P54_specs_109;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_122P54_109[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_122P54_constr_109;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_122P55;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_122P55_specs_111;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_122P55_111[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_122P55_constr_111;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_122P56;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_122P56_specs_113;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_122P56_113[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_122P56_constr_113;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_122P57;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_122P57_specs_115;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_122P57_115[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_122P57_constr_115;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_122P58;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_122P58_specs_117;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_122P58_117[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_122P58_constr_117;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_122P59;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_122P59_specs_119;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_122P59_119[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_122P59_constr_119;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_122P60;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_122P60_specs_121;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_122P60_121[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_122P60_constr_121;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_122P61;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_122P61_specs_123;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_122P61_123[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_122P61_constr_123;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_122P62;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_122P62_specs_125;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_122P62_125[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_122P62_constr_125;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_122P63;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_122P63_specs_127;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_122P63_127[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_122P63_constr_127;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_122P64;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_122P64_specs_129;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_122P64_129[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_122P64_constr_129;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ProtocolIE-Field.h"

#endif	/* _ProtocolIE_Container_H_ */
#include <asn_internal.h>
