/*
 * Generated by asn1c-1.0.0 (http://lionet.info/asn1c)
 * From ASN.1 module "S1AP-PDU-Contents"
 * 	found in "../asn1/S1AP-PDU-Contents.asn"
 * 	`asn1c -gen-PER -fcompound-names -S ../skeletons`
 */

#ifndef	_ResetAll_H_
#define	_ResetAll_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ResetAll {
	ResetAll_reset_all	= 0
	/*
	 * Enumeration is extensible
	 */
} e_ResetAll;

/* ResetAll */
typedef long	 ResetAll_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_ResetAll_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ResetAll;
extern asn_INTEGER_specifics_t asn_SPC_ResetAll_specs_1;
asn_struct_free_f ResetAll_free;
asn_struct_print_f ResetAll_print;
asn_constr_check_f ResetAll_constraint;
ber_type_decoder_f ResetAll_decode_ber;
der_type_encoder_f ResetAll_encode_der;
xer_type_decoder_f ResetAll_decode_xer;
xer_type_encoder_f ResetAll_encode_xer;
per_type_decoder_f ResetAll_decode_uper;
per_type_encoder_f ResetAll_encode_uper;
per_type_decoder_f ResetAll_decode_aper;
per_type_encoder_f ResetAll_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _ResetAll_H_ */
#include <asn_internal.h>
