/*
 * Generated by asn1c-1.0.0 (http://lionet.info/asn1c)
 * From ASN.1 module "S1AP-IEs"
 * 	found in "../asn1/S1AP-IEs.asn"
 * 	`asn1c -gen-PER -fcompound-names -S ../skeletons`
 */

#ifndef	_RIMRoutingAddress_H_
#define	_RIMRoutingAddress_H_


#include <asn_application.h>

/* Including external dependencies */
#include "GERAN-Cell-ID.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum RIMRoutingAddress_PR {
	RIMRoutingAddress_PR_NOTHING,	/* No components present */
	RIMRoutingAddress_PR_gERAN_Cell_ID
	/* Extensions may appear below */
	
} RIMRoutingAddress_PR;

/* RIMRoutingAddress */
typedef struct RIMRoutingAddress {
	RIMRoutingAddress_PR present;
	union RIMRoutingAddress_u {
		GERAN_Cell_ID_t	 gERAN_Cell_ID;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RIMRoutingAddress_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RIMRoutingAddress;
extern asn_CHOICE_specifics_t asn_SPC_RIMRoutingAddress_specs_1;
extern asn_TYPE_member_t asn_MBR_RIMRoutingAddress_1[1];
extern asn_per_constraints_t asn_PER_type_RIMRoutingAddress_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _RIMRoutingAddress_H_ */
#include <asn_internal.h>
