/*
 * Generated by asn1c-1.0.0 (http://lionet.info/asn1c)
 * From ASN.1 module "S1AP-IEs"
 * 	found in "../asn1/S1AP-IEs.asn"
 * 	`asn1c -gen-PER -fcompound-names -S ../skeletons`
 */

#include "ServedGUMMEIsItem.h"

asn_TYPE_member_t asn_MBR_ServedGUMMEIsItem_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ServedGUMMEIsItem, servedPLMNs),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ServedPLMNs,
		0,	/* Defer constraints checking to the member type */
		&asn_PER_type_ServedPLMNs_constr_1,
		0,
		"servedPLMNs"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ServedGUMMEIsItem, servedGroupIDs),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ServedGroupIDs,
		0,	/* Defer constraints checking to the member type */
		&asn_PER_type_ServedGroupIDs_constr_1,
		0,
		"servedGroupIDs"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ServedGUMMEIsItem, servedMMECs),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ServedMMECs,
		0,	/* Defer constraints checking to the member type */
		&asn_PER_type_ServedMMECs_constr_1,
		0,
		"servedMMECs"
		},
	{ ATF_POINTER, 1, offsetof(struct ServedGUMMEIsItem, iE_Extensions),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ProtocolExtensionContainer_173P33,
		0,	/* Defer constraints checking to the member type */
		&asn_PER_type_ProtocolExtensionContainer_173P33_constr_67,
		0,
		"iE-Extensions"
		},
};
static const int asn_MAP_ServedGUMMEIsItem_oms_1[] = { 3 };
static const ber_tlv_tag_t asn_DEF_ServedGUMMEIsItem_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_ServedGUMMEIsItem_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* servedPLMNs */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* servedGroupIDs */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* servedMMECs */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 } /* iE-Extensions */
};
asn_SEQUENCE_specifics_t asn_SPC_ServedGUMMEIsItem_specs_1 = {
	sizeof(struct ServedGUMMEIsItem),
	offsetof(struct ServedGUMMEIsItem, _asn_ctx),
	asn_MAP_ServedGUMMEIsItem_tag2el_1,
	4,	/* Count of tags in the map */
	asn_MAP_ServedGUMMEIsItem_oms_1,	/* Optional members */
	1, 0,	/* Root/Additions */
	3,	/* Start extensions */
	5	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_ServedGUMMEIsItem = {
	"ServedGUMMEIsItem",
	"ServedGUMMEIsItem",
	&asn_OP_SEQUENCE,
	SEQUENCE_constraint,
	asn_DEF_ServedGUMMEIsItem_tags_1,
	sizeof(asn_DEF_ServedGUMMEIsItem_tags_1)
		/sizeof(asn_DEF_ServedGUMMEIsItem_tags_1[0]), /* 1 */
	asn_DEF_ServedGUMMEIsItem_tags_1,	/* Same as above */
	sizeof(asn_DEF_ServedGUMMEIsItem_tags_1)
		/sizeof(asn_DEF_ServedGUMMEIsItem_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_ServedGUMMEIsItem_1,
	4,	/* Elements count */
	&asn_SPC_ServedGUMMEIsItem_specs_1	/* Additional specs */
};

