/*
 * Generated by asn1c-1.0.0 (http://lionet.info/asn1c)
 * From ASN.1 module "S1AP-IEs"
 * 	found in "../asn1/S1AP-IEs.asn"
 * 	`asn1c -gen-PER -fcompound-names -S ../skeletons`
 */

#include "SourceeNB-ID.h"

asn_TYPE_member_t asn_MBR_SourceeNB_ID_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SourceeNB_ID, global_ENB_ID),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Global_ENB_ID,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"global-ENB-ID"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SourceeNB_ID, selected_TAI),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TAI,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"selected-TAI"
		},
	{ ATF_POINTER, 1, offsetof(struct SourceeNB_ID, iE_Extensions),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ProtocolExtensionContainer_173P31,
		0,	/* Defer constraints checking to the member type */
		&asn_PER_type_ProtocolExtensionContainer_173P31_constr_63,
		0,
		"iE-Extensions"
		},
};
static const int asn_MAP_SourceeNB_ID_oms_1[] = { 2 };
static const ber_tlv_tag_t asn_DEF_SourceeNB_ID_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_SourceeNB_ID_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* global-ENB-ID */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* selected-TAI */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* iE-Extensions */
};
asn_SEQUENCE_specifics_t asn_SPC_SourceeNB_ID_specs_1 = {
	sizeof(struct SourceeNB_ID),
	offsetof(struct SourceeNB_ID, _asn_ctx),
	asn_MAP_SourceeNB_ID_tag2el_1,
	3,	/* Count of tags in the map */
	asn_MAP_SourceeNB_ID_oms_1,	/* Optional members */
	1, 0,	/* Root/Additions */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_SourceeNB_ID = {
	"SourceeNB-ID",
	"SourceeNB-ID",
	&asn_OP_SEQUENCE,
	SEQUENCE_constraint,
	asn_DEF_SourceeNB_ID_tags_1,
	sizeof(asn_DEF_SourceeNB_ID_tags_1)
		/sizeof(asn_DEF_SourceeNB_ID_tags_1[0]), /* 1 */
	asn_DEF_SourceeNB_ID_tags_1,	/* Same as above */
	sizeof(asn_DEF_SourceeNB_ID_tags_1)
		/sizeof(asn_DEF_SourceeNB_ID_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_SourceeNB_ID_1,
	3,	/* Elements count */
	&asn_SPC_SourceeNB_ID_specs_1	/* Additional specs */
};

