/*
 * Generated by asn1c-1.0.0 (http://lionet.info/asn1c)
 * From ASN.1 module "S1AP-IEs"
 * 	found in "../asn1/S1AP-IEs.asn"
 * 	`asn1c -gen-PER -fcompound-names -S ../skeletons`
 */

#include "SourceeNB-ToTargeteNB-TransparentContainer.h"

static asn_TYPE_member_t asn_MBR_SourceeNB_ToTargeteNB_TransparentContainer_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SourceeNB_ToTargeteNB_TransparentContainer, rRC_Container),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RRC_Container,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"rRC-Container"
		},
	{ ATF_POINTER, 1, offsetof(struct SourceeNB_ToTargeteNB_TransparentContainer, e_RABInformationList),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_E_RABInformationList,
		0,	/* Defer constraints checking to the member type */
		&asn_PER_type_E_RABInformationList_constr_1,
		0,
		"e-RABInformationList"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SourceeNB_ToTargeteNB_TransparentContainer, targetCell_ID),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_EUTRAN_CGI,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"targetCell-ID"
		},
	{ ATF_POINTER, 1, offsetof(struct SourceeNB_ToTargeteNB_TransparentContainer, subscriberProfileIDforRFP),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SubscriberProfileIDforRFP,
		0,	/* Defer constraints checking to the member type */
		&asn_PER_type_SubscriberProfileIDforRFP_constr_1,
		0,
		"subscriberProfileIDforRFP"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SourceeNB_ToTargeteNB_TransparentContainer, uE_HistoryInformation),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UE_HistoryInformation,
		0,	/* Defer constraints checking to the member type */
		&asn_PER_type_UE_HistoryInformation_constr_1,
		0,
		"uE-HistoryInformation"
		},
	{ ATF_POINTER, 1, offsetof(struct SourceeNB_ToTargeteNB_TransparentContainer, iE_Extensions),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ProtocolExtensionContainer_173P32,
		0,	/* Defer constraints checking to the member type */
		&asn_PER_type_ProtocolExtensionContainer_173P32_constr_65,
		0,
		"iE-Extensions"
		},
};
static const int asn_MAP_SourceeNB_ToTargeteNB_TransparentContainer_oms_1[] = { 1, 3, 5 };
static const ber_tlv_tag_t asn_DEF_SourceeNB_ToTargeteNB_TransparentContainer_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_SourceeNB_ToTargeteNB_TransparentContainer_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* rRC-Container */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* e-RABInformationList */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* targetCell-ID */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* subscriberProfileIDforRFP */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* uE-HistoryInformation */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 } /* iE-Extensions */
};
static asn_SEQUENCE_specifics_t asn_SPC_SourceeNB_ToTargeteNB_TransparentContainer_specs_1 = {
	sizeof(struct SourceeNB_ToTargeteNB_TransparentContainer),
	offsetof(struct SourceeNB_ToTargeteNB_TransparentContainer, _asn_ctx),
	asn_MAP_SourceeNB_ToTargeteNB_TransparentContainer_tag2el_1,
	6,	/* Count of tags in the map */
	asn_MAP_SourceeNB_ToTargeteNB_TransparentContainer_oms_1,	/* Optional members */
	3, 0,	/* Root/Additions */
	5,	/* Start extensions */
	7	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_SourceeNB_ToTargeteNB_TransparentContainer = {
	"SourceeNB-ToTargeteNB-TransparentContainer",
	"SourceeNB-ToTargeteNB-TransparentContainer",
	&asn_OP_SEQUENCE,
	SEQUENCE_constraint,
	asn_DEF_SourceeNB_ToTargeteNB_TransparentContainer_tags_1,
	sizeof(asn_DEF_SourceeNB_ToTargeteNB_TransparentContainer_tags_1)
		/sizeof(asn_DEF_SourceeNB_ToTargeteNB_TransparentContainer_tags_1[0]), /* 1 */
	asn_DEF_SourceeNB_ToTargeteNB_TransparentContainer_tags_1,	/* Same as above */
	sizeof(asn_DEF_SourceeNB_ToTargeteNB_TransparentContainer_tags_1)
		/sizeof(asn_DEF_SourceeNB_ToTargeteNB_TransparentContainer_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_SourceeNB_ToTargeteNB_TransparentContainer_1,
	6,	/* Elements count */
	&asn_SPC_SourceeNB_ToTargeteNB_TransparentContainer_specs_1	/* Additional specs */
};

