/*
 * Generated by asn1c-1.0.0 (http://lionet.info/asn1c)
 * From ASN.1 module "S1AP-IEs"
 * 	found in "../asn1/S1AP-IEs.asn"
 * 	`asn1c -gen-PER -fcompound-names -S ../skeletons`
 */

#include "SRVCCHOIndication.h"

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static asn_per_constraints_t asn_PER_type_SRVCCHOIndication_constr_1 GCC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  1,  1,  0l,  1l }	/* (0..1,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static const asn_INTEGER_enum_map_t asn_MAP_SRVCCHOIndication_value2enum_1[] = {
	{ 0,	7,	"pSandCS" },
	{ 1,	6,	"cSonly" }
	/* This list is extensible */
};
static const unsigned int asn_MAP_SRVCCHOIndication_enum2value_1[] = {
	1,	/* cSonly(1) */
	0	/* pSandCS(0) */
	/* This list is extensible */
};
static const asn_INTEGER_specifics_t asn_SPC_SRVCCHOIndication_specs_1 = {
	asn_MAP_SRVCCHOIndication_value2enum_1,	/* "tag" => N; sorted by tag */
	asn_MAP_SRVCCHOIndication_enum2value_1,	/* N => "tag"; sorted by N */
	2,	/* Number of elements in the maps */
	3,	/* Extensions before this member */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_SRVCCHOIndication_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
asn_TYPE_descriptor_t asn_DEF_SRVCCHOIndication = {
	"SRVCCHOIndication",
	"SRVCCHOIndication",
	&asn_OP_NativeEnumerated,
	NativeEnumerated_constraint,
	asn_DEF_SRVCCHOIndication_tags_1,
	sizeof(asn_DEF_SRVCCHOIndication_tags_1)
		/sizeof(asn_DEF_SRVCCHOIndication_tags_1[0]), /* 1 */
	asn_DEF_SRVCCHOIndication_tags_1,	/* Same as above */
	sizeof(asn_DEF_SRVCCHOIndication_tags_1)
		/sizeof(asn_DEF_SRVCCHOIndication_tags_1[0]), /* 1 */
	&asn_PER_type_SRVCCHOIndication_constr_1,
	0, 0,	/* Defined elsewhere */
	&asn_SPC_SRVCCHOIndication_specs_1	/* Additional specs */
};

