/*
 * Generated by asn1c-1.0.0 (http://lionet.info/asn1c)
 * From ASN.1 module "S1AP-IEs"
 * 	found in "../asn1/S1AP-IEs.asn"
 * 	`asn1c -gen-PER -fcompound-names -S ../skeletons`
 */

#ifndef	_TAIListforWarning_H_
#define	_TAIListforWarning_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct TAI;

/* TAIListforWarning */
typedef struct TAIListforWarning {
	A_SEQUENCE_OF(struct TAI) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} TAIListforWarning_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TAIListforWarning;
extern asn_SET_OF_specifics_t asn_SPC_TAIListforWarning_specs_1;
extern asn_TYPE_member_t asn_MBR_TAIListforWarning_1[1];
extern asn_per_constraints_t asn_PER_type_TAIListforWarning_constr_1;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "TAI.h"

#endif	/* _TAIListforWarning_H_ */
#include <asn_internal.h>
