/*
 * Generated by asn1c-1.0.0 (http://lionet.info/asn1c)
 * From ASN.1 module "S1AP-IEs"
 * 	found in "../asn1/S1AP-IEs.asn"
 * 	`asn1c -gen-PER -fcompound-names -S ../skeletons`
 */

#include "TargetRNC-ID.h"

asn_TYPE_member_t asn_MBR_TargetRNC_ID_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct TargetRNC_ID, lAI),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_LAI,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"lAI"
		},
	{ ATF_POINTER, 1, offsetof(struct TargetRNC_ID, rAC),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RAC,
		0,	/* Defer constraints checking to the member type */
		&asn_PER_type_RAC_constr_1,
		0,
		"rAC"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct TargetRNC_ID, rNC_ID),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RNC_ID,
		0,	/* Defer constraints checking to the member type */
		&asn_PER_type_RNC_ID_constr_1,
		0,
		"rNC-ID"
		},
	{ ATF_POINTER, 2, offsetof(struct TargetRNC_ID, extendedRNC_ID),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ExtendedRNC_ID,
		0,	/* Defer constraints checking to the member type */
		&asn_PER_type_ExtendedRNC_ID_constr_1,
		0,
		"extendedRNC-ID"
		},
	{ ATF_POINTER, 1, offsetof(struct TargetRNC_ID, iE_Extensions),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ProtocolExtensionContainer_173P40,
		0,	/* Defer constraints checking to the member type */
		&asn_PER_type_ProtocolExtensionContainer_173P40_constr_81,
		0,
		"iE-Extensions"
		},
};
static const int asn_MAP_TargetRNC_ID_oms_1[] = { 1, 3, 4 };
static const ber_tlv_tag_t asn_DEF_TargetRNC_ID_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_TargetRNC_ID_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* lAI */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* rAC */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* rNC-ID */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* extendedRNC-ID */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 } /* iE-Extensions */
};
asn_SEQUENCE_specifics_t asn_SPC_TargetRNC_ID_specs_1 = {
	sizeof(struct TargetRNC_ID),
	offsetof(struct TargetRNC_ID, _asn_ctx),
	asn_MAP_TargetRNC_ID_tag2el_1,
	5,	/* Count of tags in the map */
	asn_MAP_TargetRNC_ID_oms_1,	/* Optional members */
	3, 0,	/* Root/Additions */
	4,	/* Start extensions */
	6	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_TargetRNC_ID = {
	"TargetRNC-ID",
	"TargetRNC-ID",
	&asn_OP_SEQUENCE,
	SEQUENCE_constraint,
	asn_DEF_TargetRNC_ID_tags_1,
	sizeof(asn_DEF_TargetRNC_ID_tags_1)
		/sizeof(asn_DEF_TargetRNC_ID_tags_1[0]), /* 1 */
	asn_DEF_TargetRNC_ID_tags_1,	/* Same as above */
	sizeof(asn_DEF_TargetRNC_ID_tags_1)
		/sizeof(asn_DEF_TargetRNC_ID_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_TargetRNC_ID_1,
	5,	/* Elements count */
	&asn_SPC_TargetRNC_ID_specs_1	/* Additional specs */
};

