/*
 * Generated by asn1c-1.0.0 (http://lionet.info/asn1c)
 * From ASN.1 module "S1AP-IEs"
 * 	found in "../asn1/S1AP-IEs.asn"
 * 	`asn1c -gen-PER -fcompound-names -S ../skeletons`
 */

#include "UE-associatedLogicalS1-ConnectionItem.h"

static asn_TYPE_member_t asn_MBR_UE_associatedLogicalS1_ConnectionItem_1[] = {
	{ ATF_POINTER, 3, offsetof(struct UE_associatedLogicalS1_ConnectionItem, mME_UE_S1AP_ID),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MME_UE_S1AP_ID,
		0,	/* Defer constraints checking to the member type */
		&asn_PER_type_MME_UE_S1AP_ID_constr_1,
		0,
		"mME-UE-S1AP-ID"
		},
	{ ATF_POINTER, 2, offsetof(struct UE_associatedLogicalS1_ConnectionItem, eNB_UE_S1AP_ID),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ENB_UE_S1AP_ID,
		0,	/* Defer constraints checking to the member type */
		&asn_PER_type_ENB_UE_S1AP_ID_constr_1,
		0,
		"eNB-UE-S1AP-ID"
		},
	{ ATF_POINTER, 1, offsetof(struct UE_associatedLogicalS1_ConnectionItem, iE_Extensions),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ProtocolExtensionContainer_173P45,
		0,	/* Defer constraints checking to the member type */
		&asn_PER_type_ProtocolExtensionContainer_173P45_constr_91,
		0,
		"iE-Extensions"
		},
};
static const int asn_MAP_UE_associatedLogicalS1_ConnectionItem_oms_1[] = { 0, 1, 2 };
static const ber_tlv_tag_t asn_DEF_UE_associatedLogicalS1_ConnectionItem_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_UE_associatedLogicalS1_ConnectionItem_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* mME-UE-S1AP-ID */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* eNB-UE-S1AP-ID */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* iE-Extensions */
};
static asn_SEQUENCE_specifics_t asn_SPC_UE_associatedLogicalS1_ConnectionItem_specs_1 = {
	sizeof(struct UE_associatedLogicalS1_ConnectionItem),
	offsetof(struct UE_associatedLogicalS1_ConnectionItem, _asn_ctx),
	asn_MAP_UE_associatedLogicalS1_ConnectionItem_tag2el_1,
	3,	/* Count of tags in the map */
	asn_MAP_UE_associatedLogicalS1_ConnectionItem_oms_1,	/* Optional members */
	3, 0,	/* Root/Additions */
	2,	/* Start extensions */
	4	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_UE_associatedLogicalS1_ConnectionItem = {
	"UE-associatedLogicalS1-ConnectionItem",
	"UE-associatedLogicalS1-ConnectionItem",
	&asn_OP_SEQUENCE,
	SEQUENCE_constraint,
	asn_DEF_UE_associatedLogicalS1_ConnectionItem_tags_1,
	sizeof(asn_DEF_UE_associatedLogicalS1_ConnectionItem_tags_1)
		/sizeof(asn_DEF_UE_associatedLogicalS1_ConnectionItem_tags_1[0]), /* 1 */
	asn_DEF_UE_associatedLogicalS1_ConnectionItem_tags_1,	/* Same as above */
	sizeof(asn_DEF_UE_associatedLogicalS1_ConnectionItem_tags_1)
		/sizeof(asn_DEF_UE_associatedLogicalS1_ConnectionItem_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_UE_associatedLogicalS1_ConnectionItem_1,
	3,	/* Elements count */
	&asn_SPC_UE_associatedLogicalS1_ConnectionItem_specs_1	/* Additional specs */
};

