/*
 * Generated by asn1c-1.0.0 (http://lionet.info/asn1c)
 * From ASN.1 module "S1AP-IEs"
 * 	found in "../asn1/S1AP-IEs.asn"
 * 	`asn1c -gen-PER -fcompound-names -S ../skeletons`
 */

#include "UE-HistoryInformation.h"

asn_per_constraints_t asn_PER_type_UE_HistoryInformation_constr_1 GCC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 4,  4,  1l,  16l }	/* (SIZE(1..16)) */,
	0, 0	/* No PER value map */
};
asn_TYPE_member_t asn_MBR_UE_HistoryInformation_1[] = {
	{ ATF_POINTER, 0, 0,
		-1 /* Ambiguous tag (CHOICE?) */,
		0,
		&asn_DEF_LastVisitedCell_Item,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		""
		},
};
static const ber_tlv_tag_t asn_DEF_UE_HistoryInformation_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_UE_HistoryInformation_specs_1 = {
	sizeof(struct UE_HistoryInformation),
	offsetof(struct UE_HistoryInformation, _asn_ctx),
	2,	/* XER encoding is XMLValueList */
};
asn_TYPE_descriptor_t asn_DEF_UE_HistoryInformation = {
	"UE-HistoryInformation",
	"UE-HistoryInformation",
	&asn_OP_SEQUENCE_OF,
	SEQUENCE_OF_constraint,
	asn_DEF_UE_HistoryInformation_tags_1,
	sizeof(asn_DEF_UE_HistoryInformation_tags_1)
		/sizeof(asn_DEF_UE_HistoryInformation_tags_1[0]), /* 1 */
	asn_DEF_UE_HistoryInformation_tags_1,	/* Same as above */
	sizeof(asn_DEF_UE_HistoryInformation_tags_1)
		/sizeof(asn_DEF_UE_HistoryInformation_tags_1[0]), /* 1 */
	&asn_PER_type_UE_HistoryInformation_constr_1,
	asn_MBR_UE_HistoryInformation_1,
	1,	/* Single element */
	&asn_SPC_UE_HistoryInformation_specs_1	/* Additional specs */
};

