/*
 * Generated by asn1c-1.0.0 (http://lionet.info/asn1c)
 * From ASN.1 module "S1AP-IEs"
 * 	found in "../asn1/S1AP-IEs.asn"
 * 	`asn1c -gen-PER -fcompound-names -S ../skeletons`
 */

#include "UE-S1AP-IDs.h"

static asn_per_constraints_t asn_PER_type_UE_S1AP_IDs_constr_1 GCC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  1,  1,  0l,  1l }	/* (0..1,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_UE_S1AP_IDs_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct UE_S1AP_IDs, choice.uE_S1AP_ID_pair),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UE_S1AP_ID_pair,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uE-S1AP-ID-pair"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct UE_S1AP_IDs, choice.mME_UE_S1AP_ID),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MME_UE_S1AP_ID,
		0,	/* Defer constraints checking to the member type */
		&asn_PER_type_MME_UE_S1AP_ID_constr_1,
		0,
		"mME-UE-S1AP-ID"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_UE_S1AP_IDs_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* uE-S1AP-ID-pair */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* mME-UE-S1AP-ID */
};
static asn_CHOICE_specifics_t asn_SPC_UE_S1AP_IDs_specs_1 = {
	sizeof(struct UE_S1AP_IDs),
	offsetof(struct UE_S1AP_IDs, _asn_ctx),
	offsetof(struct UE_S1AP_IDs, present),
	sizeof(((struct UE_S1AP_IDs *)0)->present),
	asn_MAP_UE_S1AP_IDs_tag2el_1,
	2,	/* Count of tags in the map */
	0,
	2	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_UE_S1AP_IDs = {
	"UE-S1AP-IDs",
	"UE-S1AP-IDs",
	&asn_OP_CHOICE,
	CHOICE_constraint,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	&asn_PER_type_UE_S1AP_IDs_constr_1,
	asn_MBR_UE_S1AP_IDs_1,
	2,	/* Elements count */
	&asn_SPC_UE_S1AP_IDs_specs_1	/* Additional specs */
};

