/*
 * Generated by asn1c-1.0.0 (http://lionet.info/asn1c)
 * From ASN.1 module "S1AP-IEs"
 * 	found in "../asn1/S1AP-IEs.asn"
 * 	`asn1c -gen-PER -fcompound-names -S ../skeletons`
 */

#include "UEPagingID.h"

static asn_per_constraints_t asn_PER_type_UEPagingID_constr_1 GCC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  1,  1,  0l,  1l }	/* (0..1,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_UEPagingID_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct UEPagingID, choice.s_TMSI),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_S_TMSI,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"s-TMSI"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct UEPagingID, choice.iMSI),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_IMSI,
		0,	/* Defer constraints checking to the member type */
		&asn_PER_type_IMSI_constr_1,
		0,
		"iMSI"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_UEPagingID_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* s-TMSI */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* iMSI */
};
static asn_CHOICE_specifics_t asn_SPC_UEPagingID_specs_1 = {
	sizeof(struct UEPagingID),
	offsetof(struct UEPagingID, _asn_ctx),
	offsetof(struct UEPagingID, present),
	sizeof(((struct UEPagingID *)0)->present),
	asn_MAP_UEPagingID_tag2el_1,
	2,	/* Count of tags in the map */
	0,
	2	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_UEPagingID = {
	"UEPagingID",
	"UEPagingID",
	&asn_OP_CHOICE,
	CHOICE_constraint,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	&asn_PER_type_UEPagingID_constr_1,
	asn_MBR_UEPagingID_1,
	2,	/* Elements count */
	&asn_SPC_UEPagingID_specs_1	/* Additional specs */
};

