/*
 * Generated by asn1c-1.0.0 (http://lionet.info/asn1c)
 * From ASN.1 module "S1AP-IEs"
 * 	found in "../asn1/S1AP-IEs.asn"
 * 	`asn1c -gen-PER -fcompound-names -S ../skeletons`
 */

#include "WarningAreaList.h"

static asn_per_constraints_t asn_PER_type_WarningAreaList_constr_1 GCC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  2,  2,  0l,  2l }	/* (0..2,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_WarningAreaList_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct WarningAreaList, choice.cellIDList),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ECGIList,
		0,	/* Defer constraints checking to the member type */
		&asn_PER_type_ECGIList_constr_1,
		0,
		"cellIDList"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct WarningAreaList, choice.trackingAreaListforWarning),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TAIListforWarning,
		0,	/* Defer constraints checking to the member type */
		&asn_PER_type_TAIListforWarning_constr_1,
		0,
		"trackingAreaListforWarning"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct WarningAreaList, choice.emergencyAreaIDList),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_EmergencyAreaIDList,
		0,	/* Defer constraints checking to the member type */
		&asn_PER_type_EmergencyAreaIDList_constr_1,
		0,
		"emergencyAreaIDList"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_WarningAreaList_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* cellIDList */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* trackingAreaListforWarning */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* emergencyAreaIDList */
};
static asn_CHOICE_specifics_t asn_SPC_WarningAreaList_specs_1 = {
	sizeof(struct WarningAreaList),
	offsetof(struct WarningAreaList, _asn_ctx),
	offsetof(struct WarningAreaList, present),
	sizeof(((struct WarningAreaList *)0)->present),
	asn_MAP_WarningAreaList_tag2el_1,
	3,	/* Count of tags in the map */
	0,
	3	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_WarningAreaList = {
	"WarningAreaList",
	"WarningAreaList",
	&asn_OP_CHOICE,
	CHOICE_constraint,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	&asn_PER_type_WarningAreaList_constr_1,
	asn_MBR_WarningAreaList_1,
	3,	/* Elements count */
	&asn_SPC_WarningAreaList_specs_1	/* Additional specs */
};

