/*
 * Generated by asn1c-1.0.0 (http://lionet.info/asn1c)
 * From ASN.1 module "S1AP-IEs"
 * 	found in "../asn1/S1AP-IEs.asn"
 * 	`asn1c -gen-PER -fcompound-names -S ../skeletons`
 */

#include "X2TNLConfigurationInfo.h"

asn_TYPE_member_t asn_MBR_X2TNLConfigurationInfo_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct X2TNLConfigurationInfo, eNBX2TransportLayerAddresses),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ENBX2TLAs,
		0,	/* Defer constraints checking to the member type */
		&asn_PER_type_ENBX2TLAs_constr_1,
		0,
		"eNBX2TransportLayerAddresses"
		},
	{ ATF_POINTER, 1, offsetof(struct X2TNLConfigurationInfo, iE_Extensions),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ProtocolExtensionContainer_173P47,
		0,	/* Defer constraints checking to the member type */
		&asn_PER_type_ProtocolExtensionContainer_173P47_constr_95,
		0,
		"iE-Extensions"
		},
};
static const int asn_MAP_X2TNLConfigurationInfo_oms_1[] = { 1 };
static const ber_tlv_tag_t asn_DEF_X2TNLConfigurationInfo_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_X2TNLConfigurationInfo_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* eNBX2TransportLayerAddresses */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* iE-Extensions */
};
asn_SEQUENCE_specifics_t asn_SPC_X2TNLConfigurationInfo_specs_1 = {
	sizeof(struct X2TNLConfigurationInfo),
	offsetof(struct X2TNLConfigurationInfo, _asn_ctx),
	asn_MAP_X2TNLConfigurationInfo_tag2el_1,
	2,	/* Count of tags in the map */
	asn_MAP_X2TNLConfigurationInfo_oms_1,	/* Optional members */
	1, 0,	/* Root/Additions */
	1,	/* Start extensions */
	3	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_X2TNLConfigurationInfo = {
	"X2TNLConfigurationInfo",
	"X2TNLConfigurationInfo",
	&asn_OP_SEQUENCE,
	SEQUENCE_constraint,
	asn_DEF_X2TNLConfigurationInfo_tags_1,
	sizeof(asn_DEF_X2TNLConfigurationInfo_tags_1)
		/sizeof(asn_DEF_X2TNLConfigurationInfo_tags_1[0]), /* 1 */
	asn_DEF_X2TNLConfigurationInfo_tags_1,	/* Same as above */
	sizeof(asn_DEF_X2TNLConfigurationInfo_tags_1)
		/sizeof(asn_DEF_X2TNLConfigurationInfo_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_X2TNLConfigurationInfo_1,
	2,	/* Elements count */
	&asn_SPC_X2TNLConfigurationInfo_specs_1	/* Additional specs */
};

